---
title: ""
runtime: shiny
output: html_document
---

```{r, echo=FALSE,message=FALSE, warning=FALSE}

library(shiny)
library(dplyr)
library(ggplot2)
library(knitr)
library(rsconnect)
library(reshape2)
library(shinythemes)
library(shinyjs)
library(DBI)
library(RMySQL)
library(sqldf)
library(odbc)
library(httr)
library(shinyalert)
library(modeest)
library(fGarch)
library(gss)
library(DT)
library(timevis)

size <- 15
size_axis_title <- 15
lwd_errorbar <- 1
size_strip_text <- 18
pd <-position_dodge(width=0.4)
pdb <- position_dodge(width=0.8)
choicesex <-c("Male"="m","Female"="f","Male and Female"="mf")
choiceData <-c("All data"="all","Current data"="own")
choiceJitter <-c("Without data points"="without","With data points"="with")
choiceScatter <-c("Height vs midparent"="midparent","Height vs shoe size"="shoe","Height of father vs height of mother"="parents")
choiceMilk <-c("0 vs 1-10+"="Group1","0-2 vs 3-10+"="Group2","0-5 vs 6-10+"="Group3")

colsf    <- c("c1" = "#00A9FF", "c2" = "#CD9600","c3"="darkblue")
colsm    <- c("c3" = "#F8766D", "c4" = "#C77CFF","c5"="darkred")
colsb   <- c("c1" = "#00A9FF","c2"="darkblue", "c3" = "#F8766D","c4"="darkred")


ui <- fluidPage(useShinyjs(),theme = shinytheme("flatly"),withMathJax(),
 navbarPage("",           
    tabPanel("1 Data",value="idData",
          sidebarLayout(
            sidebarPanel(
              width = 4,
                  tags$head(tags$script('
                                              Shiny.addCustomMessageHandler("myCallbackHandler",
                                              function(typeMessage) {console.log(typeMessage)
                                              if(typeMessage == 1){
                                              console.log("got here");
                                              $("a:contains(2 Central tendency)").click();
                                              }
                                              if(typeMessage == 2){
                                              $("a:contains(3 Dispersion parameters)").click();
                                              }
                                              if(typeMessage == 3){
                                              $("a:contains(4 Graphics)").click();
                                              }
                                              if(typeMessage == 4){
                                              $("a:contains(5 SE and 95%CI)").click();
                                              }
                                              if(typeMessage == 5){
                                              $("a:contains(6 t-test)").click();
                                              }
                                              if(typeMessage == 6){
                                              $("a:contains(7 Simulation 1)").click();
                                              }
                                              if(typeMessage == 7){
                                              $("a:contains(8 Simulation 2)").click();
                                              }
                                              });
                                              ')),
             
              h4("1A These are your data"),
              h5("On the right side you see your current data. If you go down the list you also see data from previous studies conducted in the same way."),
              h4("1B Cases, variables, values"),
              h5(HTML(paste0("</b>","Each line represents an individual student ",
                             "<b>", "(=case).",
                             "</b>"," Each of the students has one or more characteristics",
                             "<b>"," (=variables",
                             "</b>"," , the columns, e.g. ???Sex???), for which different ", 
                              "<b>"," values",
                             "</b>"," (e.g., ???Male??? or ???Female???) are possible."))),
              h4("1C Scales"),
              h5(HTML(paste0(
"</b>","Type of information represented by a variable, determine the choice of analytical method. We can distinguish three levels of measurement:",
"<br/>","<br/>","<b>",
"Nominal scale:",
"<br/>","</b>",
"Nominal scaled data have the lowest information content. These are usually categories that are numerically coded. In the data at hand, sex (male, female) is such an example. The numerical values attributed to the categories do not have a rating but are arbitrary. Nominal scaled data are used to make statements about frequencies, other calculations are not possible.",
"<br/>","<br/>","<b>",
"Ordinal scale:",
"<br/>","</b>",
"Ordinal scaled categorical data follow a ranking. An example for ordinal scaled data are school grades: 6 is better than 4 in the Swiss system (but no numerical statement can be made about how much better a 6 is than a 4). In the data set at hand, the categorised number of milk glasses consumed per week is an ordinal scaled variable. Like nominal data, ordinal scaled data are usually used to make statements about frequencies.",
"<br/>","<br/>","<b>",
"Metric scales:",
"<br/>","</b>",
"Measurements on the metric scale have the highest information content. The exact distance between two values can be calculated. Any statistical method can be applied to data on this scale. There are two different subtypes, the ",
"<b>",
" interval",
"</b>",
" and the",
"<b>",
" ratio scale.",
"</b>",
" Whereas interval scaled data have an arbitrary zero (e.g., temperatures in degrees Celsius), ratio scaled data have a natural zero (e.g., body height). Further details can be found ",
"<a href=\"https://en.wikipedia.org/wiki/Level_of_measurement\" target=\"_blank\">","here","</a>"

))),
              
            actionButton('NextTendency','Proceed to Central tendency')
            ),
             mainPanel(width = 4,
                dataTableOutput("datatable"),
                downloadButton('downloadData1', 'Download')
            ) # end main panel
            ) # end sidebarLayout
          ) # tabPanel
    
    ,

    tabPanel("2 Central tendency", 
          sidebarLayout(
            sidebarPanel(width = 4,
              h5(HTML(paste0("Measures of the central tendency are basic elements of descriptive statistics (see ",
"<a href=\"https://en.wikipedia.org/wiki/Descriptive_statistics\" target=\"_blank\">","here","</a>",
  ") For height, it is usually recommended to analyse men and women separatedly. The most commonly used measures are:"))),
              h4("2A Mean"),
              h5(HTML(paste0("The arithmetic mean (or average) is obtained by adding up all the values and dividing this total by the number of observations. The strength of the mean is that this measure is based on all the observations in a series, the limitation is that extreme values have a large influence on the mean. Further details can be found ",
"<a href=\"https://en.wikipedia.org/wiki/Mean\" target=\"_blank\">","here","</a>",
"<br/>","<br/>",
"In the graphs on the right side, the averages of male and female height of the current study and of all data in the tool are indicated by continuous vertical lines. For comparison: Men in Switzerland are currently by average ca. 178cm tall, and women ca. 166cm."))),
              h4("2B Median"),
              h5(HTML(paste0("The median divides a sample into two equally sized halves, when the series is set out in an ascending or descending array. There are as many values below as above this value. In contrast to the mean, the median is robust against extreme values, since it only takes into account the ranking of the observations. In symmetrical distributions (like height usually is), the mean and the median are similar. 
                             Further details can be found ",
"<a href=\"https://en.wikipedia.org/wiki/Median\" target=\"_blank\">","here","</a>"))),
              h4("2C Mode"),
              h5(HTML(paste0("The mode is the most common value of a distribution. The mode is not unambiguous if several values occur with the same frequency. In this case, both expressions are called modes and the distribution is bimodal. If men and women are analysed together, the distribution of height can become almost bimodal.
                 Further details can be found ",
"<a href=\"https://de.wikipedia.org/wiki/Modus\" target=\"_blank\">","here","</a>"))),
              
              actionButton('NextDispersionparameter', 'Proceed to Dispersion parameter')
            ),
             mainPanel(
                 radioButtons(inputId = "Meanb", 
                              label = " ", 
                              choices = choiceData,
                              selected = "all"),
               plotOutput('MeanPlot'),  
               dataTableOutput('MeanTable'),
               downloadButton('downloadPlot2', 'Download Plot'),
               downloadButton('downloadData2', 'Download Table')
            ) # end mainPanel
            ) # end sidebarLayout
          ) # tabPanel
    ,
    
    tabPanel("3 Dispersion parameters", 
   
          sidebarLayout(
            sidebarPanel(width = 4,
              h5("Measures of the dispersion indicate how the data is spread around its central value. There are different ways to measure the dispersion:"),          
              h4("3A Range"),
              h5(HTML(paste0("The range simply indicates the distance between the lowest (minimum) and the highest (maximum) value in a data set. One limitation is that it fully relies on the two extreme values. Further details can be found ",
"<a href=\"https://en.wikipedia.org/wiki/Range_(statistics)\" target=\"_blank\">","here","</a>"))),
              h4("3B  Inter-quartile Range"),
              h5(HTML(paste0("The inter-quartile range (IQR) measures the distance between the first (Q1) and third (Q3) quartile (or the 25th and 75th percentiles). Thus, the IQR indicates the distance covered by the middle half of the data. It is less sensitive to extreme values than the range, but does not include all values of a series.",
                      "<br/>","<br/>",
                    "The IQR refers to the box in a so-called Boxplot, one of the standard ways to visualise the dispersion of a data set (see the example on the right side). Further details can be found ",
"<a href=\"https://en.wikipedia.org/wiki/Interquartile_range\" target=\"_blank\">","here","</a>"))),
              h4("3C Standard deviation"),
              h5(HTML(paste0("The standard deviation (SD) is the most commonly used measure of dispersion and indicates the middle dispersion of a series around the mean. The SD is the square root of the variance, which is turn calculated as the average square deviation of the individual observed values from the arithmetic mean.Further details can be found ",
"<a href=\"https://en.wikipedia.org/wiki/Standard_deviation\" target=\"_blank\">","here","</a>",
                 "<br/>","<br/>",
                 "In modern height data series, SD is usually 6.5cm."))),
              actionButton('NextDescriptive',  'Proceed to Graphics')
            ),
             mainPanel(
               tabsetPanel(
                tabPanel("Boxplot",
                radioButtons(inputId = "IQRb",
                              label = " ",
                              choices = choiceData,
                              selected = "all"),
                         
                 column(6,
                plotOutput('IQRPlot')),
                column(6,
                        plotOutput('IQRExplanation')),
     
                dataTableOutput('IQRTable'),
                downloadButton('downloadData3', 'Download Plot'),
                downloadButton('downloadTableIQR', 'Download Table')
                )
               )
             ) # end mainPanel
            ) # end sidebarLayout
          ) # tabPanel
    ,
    
        tabPanel("4 Graphics",
          sidebarLayout(
            sidebarPanel(width = 4,
              h5("As the measures of central tendency and dispersion are not telling everything about a data set it is recommended to visualise the data in order to get a more complete impression. There are a few basic types of graphs:"),
              h4("4A Histogram"),
              h5(HTML(paste0("Histograms display frequencies that are grouped in class intervals. Each bar represents the proportion of all cases falling into this category. The number/range/size of the intervals/bins on the x-axis can be defined, and the richness of details of the histogram changes (can be tested on the right side). Further details can be found ",
 "<a href=\"https://en.wikipedia.org/wiki/Histogram\" target=\"_blank\">","here","</a>"))),
              h4("4B Boxplot"),
               h5(HTML(paste0("Boxplots are used to visualise the dispersion of data sets, as the line in the middle indicates the median, the box represents the IQR and the whiskers and the outliers give an indication about the lower and upper end of a distribution. Further details can be found ",
"<a href=\"https://en.wikipedia.org/wiki/Box_plot\" target=\"_blank\">","here","</a>",
"<br/>","<br/>",
"In the exemplified height data on the right side, the effect of small sample sizes on the form of distributions is visible (you can change between all data and your data). Depending on the sample size of the current study the form of its boxplot is varying. Only in the overall study with a larger sample size the boxplot is symmetrical."))),
              h4("4C Barplot"),
              h5(HTML(paste0("Barplots are used to present frequency distributions of qualitative (nominal or ordinal) categorised data. By doing so, the absolute (count per category) or the relative frequency (proportion of the total data set located in one category) can be displayed. Further details can be found ",
             "<a href=\"https://en.wikipedia.org/wiki/Frequency_distribution\" target=\"_blank\">","here","</a>", "<br/>","<br/>",               
                "For the data set at hand, the absolute and relative frequencies of the variable milk glasses per week for men and women are displayed."))),
              h4("4D Scatterplot"),
              h5(HTML("One way of plotting two variables against each other (e.g., to explore the form and extend of an association between them) is a scatterplot (or: x-y-diagram). Each point in the could represents one pair of values of the two compared variables.
                      Further details can be found ",
                      "<a href=\"https://en.wikipedia.org/wiki/Scatter_plot\" target=\"_blank\">","here","</a>",
                      "<br/>","<br/>",
                      "Example 1: Height vs. midparent height",
 "<br/>","<br/>",
"The first example on the right side associates height with midparent height. Midparent height is usually calculated by taking the mean of maternal and paternal height, and then subtracting 6.5cm for women or adding 6.5cm for men. The point cloud reveals a positive association: Taller participants have taller mid-parent height. The straight black line and the slope result from a linear parent-offspring regression, which is usually performed in biology to estimate heritability. A slope of ca. 0.8 indicates the expected strong heritability of height. Find more information ",
"<a href=\"https://en.wikipedia.org/wiki/Heritability#Parent-offspring_regression\" target=\"_blank\">","here","</a>",
 "<br/>","<br/>",
"Examples 2 and 3: Shoe size and parents",
 "<br/>","<br/>",
"A simpler concept to assess the degree of such an association between two variables is correlation. In case of a positive correlation, high values in one variable are associated with high values in the other variable. The correlation coefficient r will always be between -1 and 0 for negative correlation, and between 0 and +1 for positive correlation. It is important to note that correlation does not mean causation. Two variables can be highly correlated without causal relationship between the two (=spurious correlation).",
 "<br/>","<br/>",
"In the case of the data set at hand, height and shoe size are strongly and positively related (r > 0.8) since taller people tend to have larger feet. Also, in modern societies taller females tend to have taller male partners (=assortative mating). In the data at hand, fathers are usually taller than mothers (most of the points are located in the lower half of the graph). Moreover, height of mothers and fathers show a moderate positive correlation (r < 0.5).")),
              
              actionButton('NextSE', 'Proceed to SE and 95%CI')
            ),
            
            mainPanel(
              tabsetPanel(
              tabPanel("4A Histogram", 
              radioButtons(inputId = "Histogramb", 
                              label = " ", 
                              choices = choiceData,
                              selected = "all"),
                sliderInput(inputId = "bin", 
                label ="Choose width of bins in cm", 
                value = 1, min = 0.1, max = 10),
                plotOutput('Histogram'),
                dataTableOutput('HistogramSummary'),
                downloadButton('downloadHistogram', 'Download Plot'),
                downloadButton('downloadSummary1', 'Download Table')
               ),
              tabPanel("4B Boxplot", 
                       radioButtons(inputId = "JitterBox", 
                              label = " ", 
                              choices = choiceJitter,
                              selected = "without"),
                plotOutput('Boxplot'),
                dataTableOutput('SampleSizeBoxplot'),
               downloadButton('downloadBoxplot', 'Download Plot'),
               downloadButton('downloadBoxplotTable', 'Download Table')
              
               ),
              tabPanel("4C Barplot", 
              radioButtons(inputId = "Barplotb", 
                              label = " ",
                              choices = c("Absolute frequencies" = "Absolute","Relative frequencies" = "Relative"),
                              selected = "Absolute"),
              
              radioButtons(inputId = "Barplotbc", 
                              label = " ", 
                              choices = choiceData,
                              selected = "all"),
              
                plotOutput('Barplot'),
                dataTableOutput('BarTablet'),
              
                downloadButton('downloadBarplot', 'Download Plot'),
                downloadButton('downloadBarplot1', 'Download Table')
            ),
            
             tabPanel("4D Scatterplot", 
              radioButtons(inputId = "Scatterplotb", 
                              label = " ", 
                              choices = choiceScatter,
                              selected = "midparent"),
               radioButtons(inputId = "Scatterplotbc", 
                              label = " ", 
                              choices = choiceData,
                              selected = "all"),
                plotOutput('Scatterplot'),
                downloadButton('downloadScatterplot', 'Download Plot')
            ) # end tabPanle
          ) # end  tabsetPanel
          ) # end  mainPanel
    ) # end sidebarLayout
    ) # tabPanel
    
    ,
    
    tabPanel("5 SE and 95%CI",

   
          sidebarLayout(
            sidebarPanel(width = 4,
              h4("5 Confidence intervals and standard errors"),
              h5(HTML(paste0("The standard error and confidence intervals are concepts that reflect the precision of an average estimate, e.g. of body height, in a sample. If a sample is drawn infinite times from the population anew, the confidence interval indicates the range which contains the true mean of the population (which is not known).",
    "<br/>","<br/>",
"Most often the 95% confidence interval is given. In this case, 95% of all samples drawn and their confidence intervals would contain the true value. The 95% confidence interval of a mean is calculated using the following formula:",
  "<br/>","<br/>",
"Mean values + 1.96 * standard error = upper limit of 95% confidence interval",
  "<br/>","<br/>",
"Mean values - 1.96 * standard error = lower limit of 95% confidence interval",
  "<br/>","<br/>",
"Further details can be found ",
"<a href=\"https://en.wikipedia.org/wiki/Confidence_interval\" target=\"_blank\">","here","</a>",
  "<br/>","<br/>",
"The standard error (SE) of an average is calculated by dividing the standard deviation (SD) by the square root of the sample size (N). Thus, the size of the standard error and the confidence interval depend on the size of the sample and the width of its distribution.
Further details can be found ",
"<a href=\"https://en.wikipedia.org/wiki/Standard_error\" target=\"_blank\">","here","</a>",
  "<br/>","<br/>",
"Because it has more women than men in the previous data set, the confidence interval around the estimate of male mean height is larger than that around the female mean. How the confidence interval changes when these parameters change can be simulated in Section 8: Simulation - 95% CI." ))),
             
              
              actionButton('NextTtest', 'Proceed to t-test')
            ),
             mainPanel(
              # uiOutput('SEText'),
            
               plotOutput('SEPlot'),
              dataTableOutput('SETablet'),
               downloadButton('downloadData4', 'Download Plot'),
               downloadButton('downloadTableSE', 'Download Table')
             ) # end mainPanel
            ) # end sidebarLayout
          ) # tabPanel
    ,
    
      tabPanel("6 t-test", 
   
          sidebarLayout(
            sidebarPanel(width = 4,
              h4("t-test"),           
              h5(HTML(paste0("There are different ways to test whether the mean values of two groups are different. One possibility are t-tests, which are part of the inference statistics, in which the population is deduced from a sample. For more information about the population see ",
"<a href=\"https://en.wikipedia.org/wiki/Statistical_population\" target=\"_blank\">","here","</a>",
" and for more information about the sample see ",
"<a href=\"https://en.wikipedia.org/wiki/Sampling_(statistics)\" target=\"_blank\">","here","</a>",
 "<br/>","<br/>",
"Hypotheses are tested:",
"<br/>","</br>",
"The H0 hypothesis usually assumes that there is no difference between the two groups, whereas the H1 hypothesis assumes a difference.",
"<br/>","</br>",
"Further details about the t-test can be found ",
"<a href=\"https://en.wikipedia.org/wiki/Student%27s_t-test\" target=\"_blank\">","here","</a>"))),

              h4("6A and 6B t-test for paired samples "),
              h5(HTML(paste0("The kind of t-test used depends on the nature of the samples. The paired t-test tests whether the mean values of two dependent samples are different. Two samples are dependent when one value in one sample and a particular value in another influence each other. This is for example the case with natural couples such as family members, as in the examples on the right (6A fathers vs. sons and 6B mothers vs. daughters).",
                               "<br/>","<br/>",
"In these concrete cases (6A and 6B) the following hypotheses are tested:", 
 "<br/>","<br/>",
"H0 - There is no difference in mean height between fathers and sons (respectively mothers and daughters).",
 "<br/>","<br/>",
"H1 - There are differences in mean height between fathers and sons (respectively mothers and daughters)."))),
#  "<br/>","<br/>",
# "The context is whether today's students are still getting taller than their parents. The t-test results in both cases (fathers vs. sons and mothers vs. daughters) in differences of less than 0.5 cm. In addition, the t-test also gives 95% confidence intervals, which include 0 for both men and women."))),

              h4("6C t-test for unpaired samples"),
              h5(HTML(paste0("The unpaired sample t-test tests whether the mean values of two independent samples are different.",
"<br/>","<br/>",
"Suppose that the main purpose of our study was to find out whether adult height depends on milk consumption. Suppose that we had some good reasons to expect such a relationship, e.g. based on our knowledge of the growth process. And suppose that we collected data on a sample of students specifically to test this hypothesis. Now we need an objective testing procedure to decide whether (or not) the data support our hypothesis. H0 is then that there is no difference in mean height between two groups of milk drinkers, while H1 assumes that milk drinkers are taller (the well-known stereotype).",
                          "<br/>","<br/>",
                        "First, however, the variable number of glasses of milk per week must be divided into two groups, a lot of milk and a little. This can be done in different ways, see the choices on the right: for example, little milk can mean 0 glasses, while much milk is one glass and more. Or a little milk is 5 glasses and less, while a lot of milk is 6 glasses and more.",
"<br/>","<br/>",
"In this example, it is only illustrated, how results can be change for different groups. However, in a study this needs to be defined before and not after the measurements and should NOT be adjusted regarding the results"))),
              # "The result of the t-test depends decisively on this assumption. According to the first definition (little=0 and much=1 or more glasses), milk drinkers are actually a few centimeters taller than me n and women who do not drink milk. The 95% confidence intervals do not include the 0, and the p-values are less than 0.05."
              #                 "<br/>","<br/>",
              # "However, this significant difference disappears when the other definitions for much and little milk are applied. This would also be more in line with the literature, when milk consumption in childhood actually promotes growth (via various channels), but milk consumption as an adult has less to do with how well one has grown as a child."))), 

              actionButton('NextSimulation', 'Proceed to Simulation 1')
            ),
             mainPanel(
              tabsetPanel(
              tabPanel("6A t-test male students vs. fathers", 
                 plotOutput('tTestMaleResultsplot'),
                 dataTableOutput('tTestMaleResults'),
                 downloadButton('downloadtTestMalePlot', 'Download Plot'),
                 downloadButton('downloadtTestMaleTable', 'Download Table')
              ),
              tabPanel("6B t-test female students vs. mothers",
                 plotOutput('tTestFemaleResultsplot'),
                 dataTableOutput('tTestFemaleResults'),
                 downloadButton('downloadtTestFemalePlot', 'Download Plot'),
                 downloadButton('downloadtTestFemaleTable', 'Download Table')
              ),
              tabPanel("6C t-test low milk consumption vs high", 
                       
                     radioButtons(inputId = "MilkGroup", 
                              label = "Number of milk glasses per week", 
                              choices = choiceMilk,
                              selected = "Group1"),
                     
                 plotOutput('tTestMilkResultsplot'),
                 dataTableOutput('tTestMilkResultsTable'),
                 downloadButton('downloadtTestMilkPlot', 'Download Plot'),
                 downloadButton('downloadtTestMilkTable', 'Download Table')
              )
              )
               # downloadButton('downloadData5', 'Download')
             ) # end mainPanel
            ) # end sidebarLayout
          ) # tabPanel
    ,
    
    tabPanel("7 Simulation - Changing distributions", 
             
   
          sidebarLayout(
            sidebarPanel(width = 4,
              h4("7 Simulation - Changing distributions"),
              h5("The distribution of a data set can change markedly if certain characteristic values of the distributions are adjusted. This will be shown here with simulated body size data (this is no longer the collected live data of the students). "),
              h4("7A Adjust the sample size"),
              h5("In a first step, the sample size of the simulated data can be adjusted (while mean and standard deviation remain the same). The graph on the left shows the result as histograms, separated for men and women, on the right the same data are shown as box plots. With decreasing or increasing sample size, the position and shape of the two distributions change only marginally. "),
              h4("7B Adjust the mean values"),
              h5("In a second step, the mean values of the two simulated distributions can be adjusted, while the sample size and standard deviation remain the same. For example, if the men are larger than the preset 178cm and the women are smaller than the preset 166cm (i.e. the sexual dimorphism would be much larger), the two histograms will shift away from each other on the x-axis, and the vertical distance between the two box plots will also be larger in the right graph. "),
               h4("7C Adjust the standard deviation"),
              h5("In a third step, the standard deviation of the two simulated distributions can be adjusted, while the sample size and mean values remain the same. For example, if you triple the women's standard deviation from 7cm to 21cm (i.e. if the variability were three times greater), the shape of the distribution becomes much wider. "),
               h4("7D Adjust the skewness"),
              h5("Most body size distributions are approximately symmetrical, i.e. there are most medium-sized men or women, and more or less equally tall and short men or women. Theoretically, however, such a distribution could also be skewed if there are more tall than short men or women (= right-skewed), or vice versa (more short = left-skewed). The measure for this phenomenon is skewness. The example on the right shows this when the skewness of 0 (=symmetric) becomes right-skewed towards +4 (=too many tall ones) or left-skewed towards -4 (=too many short ones). "),
              actionButton('NextSimulation2', 'Proceed to Simulation 2')
            ),
             mainPanel(
               tabsetPanel(
              tabPanel("7A Adjust the sample size", 
                       splitLayout(cellWidths = c("50%", "50%"), plotOutput('SimulationSamplesizeHistPlot'), 
                                   plotOutput("SimulationSamplesizeBoxPlot")),
              sliderInput(inputId = "SamplesizeMenb", 
              label = "Choose sample size men", 
              value = 100, min = 1, max = 250),
              sliderInput(inputId = "SamplesizeWomenb", 
              label = "Choose sample size women", 
              value = 100, min = 1, max = 250)
               ),
              tabPanel("7B Adjust the mean values", 
                    splitLayout(cellWidths = c("50%", "50%"),plotOutput('SimulationMeanHistPlot'), 
                                plotOutput('SimulationMeanBoxPlot')),
              sliderInput(inputId = "MeanMenb", 
              label = "Choose mean hight men", 
              value = 178 , min = 140, max = 200),
              sliderInput(inputId = "MeanWomenb", 
              label = "Choose mean hight women", 
              value = 166, min = 140, max = 200)
               ),
              tabPanel("7C Adjust the standard deviation",
                        splitLayout(cellWidths = c("50%", "50%"), plotOutput('SimulationSDHistPlot'), 
                                 plotOutput('SimulationSDBoxPlot')),
              sliderInput(inputId = "SDmenb", 
              label = "Choose standard deviation men ", 
              value = 7 , min = 1, max = 30),
              sliderInput(inputId = "SDwomenb", 
              label = "Choose standard deviation women", 
              value = 7, min = 1, max = 30)
               ),
              # tabPanel("7D Outliers",
              # plotOutput('SimulationOutliersPlot')
              #  ),
             tabPanel("7D Adjust the skewness",
                      splitLayout(cellWidths = c("50%", "50%"), plotOutput('SimulationShapeHistPlot'), 
                                 plotOutput('SimulationShapeBoxPlot')),
              sliderInput(inputId = "Shape", 
              label = "Choose skewness", 
              value = 1 , min = 0.1, max = 2)
               )
               )
                 
            )
            )
          ),
    tabPanel("8 Simulation - 95% CI", 
             
        
   
          sidebarLayout(
            sidebarPanel(width = 4,
              h4("8 Simulation - 95% confidence intervals"),
              h5("As shown in Chapter 3, a confidence interval reflects the precision of a mean estimate. A confidence interval is calculated based on the standard error (SE) for which the standard deviation (SD) is divided by the square root of the sample size. The confidence interval size changes markedly when the sample size or standard deviation changes. This is shown here using simulated data"),
              h4("8A Adjust sample size"),
              h5("If the sample size is increased (while SD remains the same), the confidence interval becomes smaller (because sample size is in the denominator of the calculation formula). The precision of the mean value estimate thus increases. With small samples, on the other hand, the confidence interval increases (for example, with only 10 men, the true mean could be 174cm or 183cm instead of 178cm)."),
              h4("8B Adjust mean values"),
              h5("If only the mean values of the samples are changed, but not SD or sample size, then the position of the mean value estimates on the y-axis changes, but not the size of the confidence interval."),
              h4("8C Adjust standard deviation"),
              h5("If SD is increased (while the sample size remains the same), the confidence interval is increased (because SD is in the numerator of the calculation formula). The precision of the mean value estimation thus decreases the wider the distribution, and vice versa.")),
             mainPanel(
               tabsetPanel(
              tabPanel("8A Adjust sample size", 
              plotOutput('SimulationCISamplesizePlot'),
              sliderInput(inputId = "SamplesizeCIMenb", 
              label = "Choose sample size men", 
              value = 100, min = 1, max = 200),
              sliderInput(inputId = "SamplesizeCIWomenb", 
              label = "Choose sample size women", 
              value = 100, min = 1, max = 200)
              ),
              tabPanel("8B Adjust mean values", 
              plotOutput('SimulationCIMeanPlot'),
              sliderInput(inputId = "MeanCIMenb", 
              label = "Choose Hight Mean Men", 
              value = 178 , min = 140, max = 200),
              sliderInput(inputId = "MeanCIWomenb", 
              label = "Choose Hight Mean Women", 
              value = 166, min = 140, max = 200)
               ),
              tabPanel("8C Adjust standard deviation", 
              plotOutput('SimulationCISDPlot'),
              sliderInput(inputId = "SDCImenb", 
              label = "Choose standard deviation men", 
              value = 7 , min = 1, max = 30),
              sliderInput(inputId = "SDCIwomenb", 
              label = "Choose standard deviation women", 
              value = 7, min = 1, max = 30)
               ) # end tabpanel
               ) # end tabsetPanel
                 
            ) # end main panel
            ) # end sidebarLayout
          
       )  # end   tabPanel
    )      # navbarPage
) # end fluitpage
              
 

server<- function(input, output, session) { 
  
# # # # # # # # # # # # # #   
# first navbarpage - data # 
# # # # # # # # # # # # # # 

# load data
new_data <- 
      reactive({
      conn <- dbConnect(
      drv = RMySQL::MySQL(),
      dbname = "******",
      host = "sql2.freemysqlhosting.net",
      username = "******",
      password = "******")
      on.exit(dbDisconnect(conn), add = TRUE)
      sql <- "SELECT * FROM heighttool"
      query <- sqlInterpolate(conn, sql)
      new_data  <- dbGetQuery(conn, query)
  })


 data_all <- reactive({
   data <- new_data()
   data$Study <- as.factor(data$Study)
   data$Sex <- as.factor(data$Sex)
   data$Height_self <- as.numeric(data$Height_self)
   data <- data[!(data$Height_self==130),]
   data <- data[!(data$Height_self==220),]
   data$Height_father <- as.numeric(data$Height_father)
   data <- data[!(data$Height_father==130),]
   data <- data[!(data$Height_father==220),]
   data$Height_mother <- as.numeric(data$Height_mother)
   data <- data[!(data$Height_mother==130),]
   data <- data[!(data$Height_mother==220),]
   data$Milk <- as.factor(data$Milk)
   data$Shoe_size <- round(as.numeric(data$Shoe_size))
   data <- data[!is.na(data$Height_self),]
   data_all <- data
   return(data_all)
   })
 
 length_maxstudy <- reactive({
 length_maxstudy <- length(which(data_all()$Study== "Current"))
 return(length_maxstudy)
 })

data <- reactive({ 
    data <- data_all()
    data$Study <- as.factor(data$Study)
    if(length_maxstudy() < 5){
         data <-  data[!data$Study=="Current",]
    return(data)
   }
   else{
      data <- data
     return(data)
   }
  })
 
# show data
datatablet <- reactive({ 
  data_print <- data()
  data_print$Study <- as.factor(data_print$Study)
  data_print <- data_print[order(data_print$Study,decreasing = FALSE),]
  data_print$Sex <- as.character(data_print$Sex)
  data_print$Sex[data_print$Sex==1] <- "Male"
  data_print$Sex[data_print$Sex==2] <- "Female"
  data_print$Height_self <- round(as.numeric(data_print$Height_self,1))
  data_print$Height_father <- round(data_print$Height_father,1)
  data_print$Height_mother <- round(data_print$Height_mother,1)
  data_print$Milk  <- as.character(data_print$Milk)
  data_print$Milk[data_print$Milk=="0"] <- "0"
  data_print$Milk[data_print$Milk=="1"] <- "1-2"
  data_print$Milk[data_print$Milk=="2"] <- "3-5"
  data_print$Milk[data_print$Milk=="3"] <- "6-9"
  data_print$Milk[data_print$Milk=="4"] <- "10+"
  data_print$Shoe_size <- as.factor(data_print$Shoe_size)
  data_print$Study <- as.factor(data_print$Study)
  colnames(data_print) <- c("Study","Sex","Height in cm","Height in cm - father","Height in cm - mother","Glasses milk per week","Shoe size")
  data_print <- as.data.frame(data_print)
  rownames(data_print) <- c()
  return(data_print)
  })


output$datatable <- renderDataTable({
  datatable(datatablet(),options = list(bFilter=0))
})


# download data

output$downloadData1 <- downloadHandler(
    filename = function() {
      paste("data","xls", sep = ".")
	  },
    content = function(file) {
      write.table(data(), file, sep="\t",row.names=FALSE)
    }
    )

observe({
    if(input$NextTendency > 0){
      session$sendCustomMessage("myCallbackHandler", "1")
    }
})

# # # # # # # # # # # # # # #  #
# second navbarpage - graphics # 
# # # # # # # # # # # # # # #  #

##############
# Histogramm #
##############

# reduce data to "own" or "all"

dataHistogram <- reactive({
 if (input$Histogramb == "all") {
 dataHistogram <- data()
 }
  else {
    dataHistogram <- data()
    dataHistogram$Study <- as.factor(dataHistogram$Study)
    dataHistogram <- dataHistogram[dataHistogram$Study=="Current",]
    }
 return(dataHistogram)
 })

# plot histogram

bin <- reactive({
    bin <- input$bin
    })

output$Histogram <- renderPlot({
  if(input$Histogramb == "own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
  }
  
  else if(input$Histogramb == "own" & length(which(data()$Study=="Current"))!=0) {
  ggplot()+
  geom_histogram(data=dataHistogram(), aes(x=Height_self,fill = Sex),alpha = 0.5,position="identity",color="darkgrey",binwidth=bin())+
  xlab("Height in cm")+
  ylab("Count") +

  scale_color_manual(name = " ",
                                breaks = c("1", "2"),
                                values = c("#00A9FF","#F8766D"),
                                labels = c("Men", "Women"))+

  scale_fill_manual(name = " ",
                               breaks = c("1", "2"),
                                values = c("#00A9FF","#F8766D"),
                                 labels = c("Men", "Women"))+

   theme_bw()+
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
         legend.key.size=unit(1.5,"cm"))
  }
  else if(input$Histogramb == "all"){
    ggplot()+
  geom_histogram(data=dataHistogram(), aes(x=Height_self,fill = Sex),alpha = 0.5,position="identity",color="darkgrey",binwidth=bin())+
  xlab("Height in cm")+
  ylab("Count") +
      
  scale_color_manual(name = " ", 
                                breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                labels = c("Men", "Women"))+
      
  scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                 labels = c("Men", "Women"))+
      
   theme_bw()+    
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
         legend.key.size=unit(1.5,"cm"))
  }
})


PlotHistogram <- reactive({
  if(input$Histogramb == "own" & length(dataHistogram()[dataHistogram()$Study=="Current"])==0) {
    return(NULL)
  }
  else {
  ggplot()+
  geom_histogram(data=dataHistogram(), aes(x=Height_self,fill = Sex),alpha = 0.5,position="identity",color="darkgrey",binwidth=bin())+
  xlab("Height in cm")+
  ylab("Count") +
      
  scale_color_manual(name = " ", 
                                breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                  labels = c("Men", "Women"))+
      
  scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                 labels = c("Men", "Women"))+
   theme_bw()+        
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
  }
})

output$downloadHistogram <- downloadHandler(
    filename = function() { paste("PlotHistogram", 'pdf', sep='.') },
    content = function(file) {
      ggsave(file,PlotHistogram())
    }
  )

# table summary
dataHistogramSummary <- reactive({
  if(input$Histogramb == "own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
  }
  
  else if(input$Histogramb == "own" & length(which(data()$Study=="Current"))!=0) {
    dataset <- dataHistogram()
    data_N <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=length)
    data_min <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=min,na.rm=TRUE)
    data_max <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=max,na.rm=TRUE)
    data_summarytext <- data.frame(N= data_N,min=data_min,max=data_max)
    data_summarytext <- data_summarytext[,c(2,4,6)]
    datadiff <- apply(data_summarytext,2,diff)
    data_diff <- as.numeric(datadiff)
    dataHistogramSummary <- rbind(data_summarytext,data_diff)
    dataHistogramSummary$Sex <- c("Men","Women","Difference")
    dataHistogramSummary <- dataHistogramSummary[,c(4,1,2,3)]
    colnames(dataHistogramSummary)  <-c("Sex","Sample size","Min in cm","Max in cm")
    dataHistogramSummary[,2] <- as.integer(dataHistogramSummary[,2])
    dataHistogramSummary[,3] <- round(dataHistogramSummary[,3],1)
    dataHistogramSummary[,4] <- round(dataHistogramSummary[,4],1)
    dataHistogramSummary <- as.data.frame(dataHistogramSummary)
    rownames(dataHistogramSummary) <-c()
  }
    else if (input$Histogramb == "all"){
    dataset <- dataHistogram()
    data_N <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=length)
    data_min <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=min,na.rm=TRUE)
    data_max <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=max,na.rm=TRUE)
    data_summarytext <- data.frame(N= data_N,min=data_min,max=data_max)
    data_summarytext <- data_summarytext[,c(2,4,6)]
    datadiff <- apply(data_summarytext,2,diff)
    data_diff <- as.numeric(datadiff)
    dataHistogramSummary <- rbind(data_summarytext,data_diff)
    dataHistogramSummary$Sex <- c("Men","Women","Difference")
    dataHistogramSummary <- dataHistogramSummary[,c(4,1,2,3)]
    colnames(dataHistogramSummary)  <-c("Sex","Sample size","Min in cm","Max in cm")
    dataHistogramSummary[,2] <- as.integer(dataHistogramSummary[,2])
    dataHistogramSummary[,3] <- round(dataHistogramSummary[,3],1)
    dataHistogramSummary[,4] <- round(dataHistogramSummary[,4],1)
    dataHistogramSummary <- as.data.frame(dataHistogramSummary)
    rownames(dataHistogramSummary) <-c()
    }
      return(dataHistogramSummary)
  })


output$HistogramSummary <- renderDataTable({
  if(input$Histogramb == "own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
  }
  else if (input$Histogramb == "own" & length(which(data()$Study=="Current"))!=0) {
  datatable(dataHistogramSummary(),options = list(dom = 't'),rownames= FALSE)%>%formatStyle('Sex',target = 'row',color = styleEqual(c("Men", "Women"),    c('#00A9FF', '#F8766D')))
  }
  else if(input$Histogramb == "all"){
  datatable(dataHistogramSummary(),options = list(dom = 't'),rownames= FALSE)%>%formatStyle('Sex',target = 'row',color = styleEqual(c("Men", "Women"), c('#00A9FF', '#F8766D')))
  }
})

output$downloadSummary1 <- downloadHandler(
    filename = function() {
      paste("Summary_Min_Max","xls", sep = ".")
	  },
    content = function(file) {
      write.table(dataHistogramSummary(), file, sep="\t",row.names=FALSE)
    }
    )

###########
# Boxplot #
###########

# plot Boxplot

output$Boxplot <- renderPlot({
 if (input$JitterBox == "without"  & length(which(data()$Study=="Current"))==0) {
    ggplot()+
          geom_boxplot(data=data(),aes(x="All",y=Height_self,fill=Sex),position=pdb)+    
           xlab("Study")+
           ylab("Height in cm")+
            scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                               labels = c("Men", "Women"))+
      scale_color_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                               labels = c("Men", "Women"))+
   theme_bw()+
   theme(axis.ticks.x=element_blank(),
         # aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
 }
  
 else if (input$JitterBox == "without"  & length(which(data()$Study=="Current"))!=0) {
    ggplot()+
          geom_boxplot(data=data()[data()$Study=="Current",],aes(x=Study,y=Height_self,fill=as.factor(Sex)),position=pdb)+
          geom_boxplot(data=data(),aes(x="All",y=Height_self,fill=Sex),position=pdb)+    
           xlab("Study")+
           ylab("Height in cm")+
            scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                               labels = c("Men", "Women"))+
      scale_color_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                               labels = c("Men", "Women"))+
   theme_bw()+
   theme(axis.ticks.x=element_blank(),
         # aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
}

  
else if (input$JitterBox == "with"  & length(which(data()$Study=="Current"))==0) {
    ggplot()+
          geom_boxplot(data=data(),aes(x="All",y=Height_self,fill=Sex),position=pdb,outlier.shape=NA)+    
          geom_jitter(data=data(),aes(x="All",y=Height_self,color=as.factor(Sex)),position=position_jitterdodge())+
           xlab("Study")+
           ylab("Height in cm")+
            scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                               labels = c("Men", "Women"))+
      scale_color_manual(name = " ",
                               breaks = c("1", "2"),
                                values = c("black","black"),
                               labels = c("Men", "Women"))+
   theme_bw()+
   theme(axis.ticks.x=element_blank(),
         # aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
}
  
  else if (input$JitterBox == "with"  & length(which(data()$Study=="Current"))!=0) {
    ggplot()+
          geom_boxplot(data=data()[data()$Study=="Current",],aes(x= Study,y=Height_self,fill=as.factor(Sex)),position=pdb,outlier.shape=NA)+
          geom_jitter(data=data()[data()$Study=="Current",],aes(x=Study,y=Height_self,color=as.factor(Sex)),
                      position=position_jitterdodge())+
          geom_boxplot(data=data(),aes(x="All",y=Height_self,fill=Sex),position=pdb,outlier.shape=NA)+    
          geom_jitter(data=data(),aes(x="All",y=Height_self,color=as.factor(Sex)),position=position_jitterdodge())+
           xlab("Study")+
           ylab("Height in cm")+
            scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                               labels = c("Men", "Women"))+
      scale_color_manual(name = " ",
                               breaks = c("1", "2"),
                                values = c("black","black"),
                               labels = c("Men", "Women"))+
   theme_bw()+
   theme(axis.ticks.x=element_blank(),
         # aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
  }
})


PlotBoxplot <- reactive({
 if (input$JitterBox == "without") {
    ggplot()+
          geom_boxplot(data=data(),aes(x= Study,y=Height_self,fill=as.factor(Sex)),position=pdb)+
          geom_boxplot(data=data(),aes(x="All",y=Height_self,fill=Sex),position=pdb)+    
           xlab("Study")+
           ylab("Height in cm")+
            scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                               labels = c("Men", "Women"))+
      scale_color_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                               labels = c("black", "black"))+
   theme_bw()+
   theme(axis.ticks.x=element_blank(),
         # aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
}

else if (input$JitterBox == "with") {
    ggplot()+
          geom_boxplot(data=data(),aes(x= Study,y=Height_self,fill=as.factor(Sex)),position=pdb,outlier.shape=NA)+
          geom_jitter(data=data(),aes(x=Study,y=Height_self,color=as.factor(Sex)),
                      position=position_jitterdodge())+
          geom_boxplot(data=data(),aes(x="All",y=Height_self,fill=Sex),position=pdb,outlier.shape=NA)+    
          geom_jitter(data=data(),aes(x="All",y=Height_self,color=as.factor(Sex)),position=position_jitterdodge())+
      
           xlab("Study")+
           ylab("Height in cm")+
            scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                               labels = c("Men", "Women"))+
      scale_color_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("black","black"),
                               labels = c("Men", "Women"))+
   theme_bw()+
   theme(axis.ticks.x=element_blank(),
         # aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
  }
})


output$downloadBoxplot <- downloadHandler(
    filename = function() { paste("PlotBoxplot", 'pdf', sep='.') },
    content = function(file) {
      ggsave(file,PlotBoxplot())
    }
  )


data_sample <- reactive({
        data_s <- data()
        data_sample <- aggregate(data_s$Height_self,by=list(data_s$Sex,data_s$Study), FUN=length) 
        colnames(data_sample) <- c("Sex","Study","Sample size")
        return(data_sample)
})

data_sample_all <- reactive({
        data_s_all <- data()
        data_sample_all <- aggregate(data_s_all$Height_self,by=list(data_s_all$Sex), FUN=length) 
        data_sample_all$Study <- "All"
        data_sample_all <- data_sample_all[,c(1,3,2)]
        colnames(data_sample_all) <- c("Sex","Study","Sample size")
        return(data_sample_all)
})


data_sample_size_all <- reactive({
data_sample_size_all<- rbind(data_sample(),data_sample_all())
data_sample_size_all$Sex <- as.character(data_sample_size_all$Sex)
  data_sample_size_all$Sex[data_sample_size_all$Sex==1] <- "Men"
  data_sample_size_all$Sex[data_sample_size_all$Sex==2] <- "Women"
  colnames(data_sample_size_all) <- c("Sex","Study","Sample size")
  data_sample_size_all <- as.data.frame(data_sample_size_all)
  rownames(data_sample_size_all) <- c()
  if (length(which(data()$Study=="Current"))==0){
    data_sample_size_all <- data_sample_size_all[data_sample_size_all$Study=="All",]
  }
  else if (length(which(data()$Study=="Current"))!=0){
    data_sample_size_all <- data_sample_size_all[!data_sample_size_all$Study=="Previous",]
  }
  return(data_sample_size_all)
})


output$SampleSizeBoxplot <- renderDataTable({
  datatable(data_sample_size_all(),options = list(dom = 't'),rownames= FALSE)%>%formatStyle('Sex',target = 'row',color = styleEqual(c("Men", "Women"), c('#00A9FF', '#F8766D')))
})

output$downloadBoxplotTable <- downloadHandler(
    filename = function() {
      paste("Summary_Boxplot","xls", sep = ".")
	  },
    content = function(file) {
      write.table(data_sample_size_all(), file, sep="\t",row.names=FALSE)
    }
    )



##############
# Barplot #
##############

# plot Barplot
dataBarplot <- reactive({
 if (input$Barplotbc == "all") {
 dataBarplot <- data()
 }
  else {
    dataBarplot <- data()
    dataBarplot <- dataBarplot[dataBarplot$Study=="Current",]
    }
 return(dataBarplot)
 })

 data_bar <- reactive({
  data_bar <- dataBarplot()[!is.na(dataBarplot()$Milk),]
  return(data_bar)
})

data_freq <- reactive({
  data_freq <- data_bar() %>% group_by(Sex,Milk) %>% dplyr::summarize(n=n()) %>% mutate(freq=n/sum(n))  
  data_freq <- as.data.frame(data_freq)
  })

output$Barplot <- renderPlot({
   if(input$Barplotbc == "own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
   }
  
  else if(input$Barplotbc == "own" & length(which(data()$Study=="Current"))!=0  & input$Barplotb == "Absolute") {
   ggplot()+
  geom_bar(data=data_freq(),aes(x=Milk,y=n,fill=as.factor(Sex)),stat="identity",position = "dodge")+
  xlab("Number of milk glasses per week")+
  ylab("Absolute count") +
  scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                labels = c("Men", "Women"))+
  scale_x_discrete(labels = c('0','1-3','3-5',"6-9","10+"))+    
  theme_bw()+    
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
  }
  else if(input$Barplotbc == "all"  & input$Barplotb == "Absolute") {
  ggplot()+
  geom_bar(data=data_freq(),aes(x=Milk,y=n,fill=as.factor(Sex)),stat="identity",position = "dodge")+
  xlab("Number of milk glasses per week")+
  ylab("Absolute count") +
  scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                labels = c("Men", "Women"))+
  scale_x_discrete(labels = c('0','1-3','3-5',"6-9","10+"))+    
  theme_bw()+    
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
  }
  else if(input$Barplotbc == "own" & length(which(data()$Study=="Current"))!=0  & input$Barplotb == "Relative") {
  ggplot()+
  geom_bar(data=data_freq(),aes(x=Milk,y=freq,fill=as.factor(Sex)),stat="identity",position = "dodge")+
  xlab("Number of milk glasses per week")+
  ylab("Proportion") +
  scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                labels = c("Men", "Women"))+
  scale_x_discrete(labels = c('0','1-3','3-5',"6-9","10+"))+   
  theme_bw()+
  theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
        legend.key.size=unit(1.5,"cm"))
  }
  
   else if(input$Barplotbc == "all" & input$Barplotb == "Relative") {
  ggplot()+
  geom_bar(data=data_freq(),aes(x=Milk,y=freq,fill=as.factor(Sex)),stat="identity",position = "dodge")+
  xlab("Number of milk glasses per week")+
  ylab("Proportion") +
  scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                labels = c("Men", "Women"))+
  scale_x_discrete(labels = c('0','1-3','3-5',"6-9","10+"))+   
  theme_bw()+
  theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
        legend.key.size=unit(1.5,"cm"))
  }
})


PlotBarplot <- reactive({
   if(input$Barplotbc == "own" & length(dataBarplot()[dataBarplot()$Study=="Current"])==0) {
    return(NULL)
  }
  else if(input$Barplotb == "Absolute") {
  ggplot()+
  geom_bar(data=data_freq(),aes(x=Milk,y=n,fill=as.factor(Sex)),stat="identity",position = "dodge")+
  xlab("Number of milk glasses per week")+
  ylab("Absolute count") +
  scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                labels = c("Men", "Women"))+
      theme_bw()+
      theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
  }
  else {
  ggplot()+
  geom_bar(data=data_freq(),aes(x=Milk,y=freq,fill=as.factor(Sex)),stat="identity",position = "dodge")+
  xlab("Number of milk glasses per week")+
  ylab("Frequency") +
  scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                labels = c("Men", "Women"))+
   theme_bw()+
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
  }
  
})

 data_bar_t <- reactive({
  data_bar_t <- data_freq()
  data_bar_t$freq <- round(data_bar_t$freq,2)
  data_bar_t$Milk <- as.character(data_bar_t$Milk)
  data_bar_t$Milk[data_bar_t$Milk=="0"] <- "0"
  data_bar_t$Milk[data_bar_t$Milk=="1"] <- "1-2"
  data_bar_t$Milk[data_bar_t$Milk=="2"] <- "3-5"
  data_bar_t$Milk[data_bar_t$Milk=="3"] <- "6-9"
  data_bar_t$Milk[data_bar_t$Milk=="4"] <- "10+"
  colnames(data_bar_t) <- c("Sex","Glases of milk","Count","Proportion")
  data_bar_t$Sex <- as.character(data_bar_t$Sex)
  data_bar_t$Sex[data_bar_t$Sex==1] <- "Men"
  data_bar_t$Sex[data_bar_t$Sex==2] <- "Women"
  data_bar_t <- as.data.frame(data_bar_t)
  rownames(data_bar_t) <- c()
  return(data_bar_t)
})

output$BarTablet <- renderDataTable({
  if(input$Barplotbc == "own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
  }
  else if(input$Barplotbc == "own" & length(which(data()$Study=="Current"))!=0) {
 datatable(data_bar_t(),options = list(pageLength = 10,dom = 't'),rownames= FALSE)%>%formatStyle('Sex',target = 'row',color = styleEqual(c("Men", "Women"), c('#00A9FF', '#F8766D')))
  }
 else if(input$Barplotbc == "all"){
  datatable(data_bar_t(),options = list(pageLength = 10,dom = 't'),rownames= FALSE)%>%formatStyle('Sex',target = 'row',color = styleEqual(c("Men", "Women"), c('#00A9FF', '#F8766D')))
  }
})

output$downloadBarplot <- downloadHandler(
    filename = function() { paste("PlotBarplot", 'pdf', sep='.') },
    content = function(file) {
      ggsave(file,PlotBarplot())
    }
  )

output$downloadBarplot1 <- downloadHandler(
    filename = function() {
      paste("Barplot","xls", sep = ".")
	  },
    content = function(file) {
      write.table(data_freq(), file, sep="\t",row.names=FALSE)
    }
    )

###############
# Scatterplot #
###############

# plot Scatterplot

midparentm <- reactive({
  midparentm <- ((data()[data()$Sex==1,]$Height_father + data()[data()$Sex==1,]$Height_mother)/2)+6.5
  midparentm <- as.data.frame(midparentm)
  colnames(midparentm) <- c("midparent")
  return(midparentm)
})

midparentm2 <- reactive({
  midparentm2 <- cbind(data()[data()$Sex==1,],midparentm())
  midparentm2 <- as.data.frame(midparentm2)
return(midparentm2)
})

midparentf <- reactive({
  midparentf <- ((data()[data()$Sex==2,]$Height_father + data()[data()$Sex==2,]$Height_mother)/2)-6.5
  midparentf <- as.data.frame(midparentf)
  colnames(midparentf) <- c("midparent")
  return(midparentf)
})

midparentf2 <- reactive({
  midparentf2 <- cbind(data()[data()$Sex==2,],midparentf())
   midparentf2 <- as.data.frame(midparentf2)
return(midparentf2)
})

dataScatterplottmp <- reactive({
  dataScatterplottmp <- rbind(midparentm2(),midparentf2())
return(dataScatterplottmp)
})

dataScatterplot <- reactive({
 if (input$Scatterplotbc == "all") {
 dataScatterplot <- dataScatterplottmp()
 }
  else {
    dataScatterplot <- dataScatterplottmp()
    dataScatterplot <- dataScatterplot[dataScatterplot$Study=="Current",]
    dataScatterplot$Study <- as.factor(dataScatterplot$Study)
    }
 return(dataScatterplot)
 })


scatter_line <- data.frame(x=seq(150,200),y=seq(150,200))

cor_shoe <-  reactive({
  cor_shoe <- cor.test(dataScatterplot()$Height_self,dataScatterplot()$Shoe_size,method="pearson",
                       use="complete.obs")
  cor_shoe <- as.character(round(cor_shoe$estimate,2))
})


slope_midpar <- reactive({  
  lm_midpar <- lm(dataScatterplot()$Height_self ~ dataScatterplot()$midparent)
  slope_midpar <- as.numeric(round(lm_midpar$coefficients[2],2))
  return(slope_midpar)
})

cor_midpar <- reactive({  
  cor_midpar <- cor(dataScatterplot()$Height_self,dataScatterplot()$midparent,use="complete.obs",method="pearson")
  cor_midpar <- as.character(round(cor_midpar,2))
})

rsquared_midpar <-  reactive({  
  rsquared_midpar <- cor(dataScatterplot()$Height_self,dataScatterplot()$midparent,use="complete.obs",method="pearson")
   rsquared_midpar <- as.character(round( rsquared_midpar^2,2))
  return(rsquared_midpar)
})

cor_parents <-  reactive({
  cor_parents <- cor.test(dataScatterplot()$Height_father,dataScatterplot()$Height_mother,method="pearson",
                          use="complete.obs")
  cor_parents <- as.character(round(cor_parents$estimate,2))
})

output$Scatterplot <- renderPlot({
  if(is.null(data())) { }
  else if(input$Scatterplotb == "midparent" & input$Scatterplotbc =="all") {
    ggplot()+
    geom_point(data=dataScatterplot(),aes(x=midparent,y=Height_self,col=Study),lwd=4)+
    geom_smooth(data=dataScatterplot(),aes(x=midparent,y=Height_self),method = "lm", color="black",se = FALSE)+
    geom_point(data=subset(dataScatterplot(),Study=="Current"),aes(x=midparent,y=Height_self,col= Study),lwd=4)+
    geom_line(data=scatter_line,aes(x=x, y=y),color="grey",lwd=0.8)+
    # annotate("text", x=180, y=165,size = 6, label= paste("r = ",cor_midpar()))+
    # annotate("text", x=180, y=160,size = 6, label= paste("r-squared = ",rsquared_midpar()))+
     annotate("text",  x=160, y=195,size = 8, label= paste("slope = ",slope_midpar()))+
    scale_y_continuous(breaks=seq(150, 200, 10))+
    scale_x_continuous(breaks=seq(150, 200, 10))+
    ylab("Height in cm ")+
    xlab("Midparents Height in cm") +
    scale_color_manual(name = "Study", 
                               breaks = c("Current", "Previous"), 
                               values = c("#00A9FF","#CD9600"),
                               labels = c("Current", "Previous"))+
    theme_bw()+
    theme(axis.ticks.x=element_blank(),
          aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
  }
  
  else if(input$Scatterplotb == "shoe"  & input$Scatterplotbc =="all") {
  ggplot()+
   geom_point(data=dataScatterplot(),aes(x=Height_self, y=Shoe_size,col=Study),lwd=4)+
   geom_smooth(data=dataScatterplot(),aes(x=Height_self, y=Shoe_size),color="black",method = "lm", se = FALSE)+
   geom_point(data=subset(dataScatterplot(),Study=="Current"),aes(x=Height_self, y=Shoe_size,col=Study),lwd=4)+
   annotate("text", x=165, y=46,  size = 8,label=paste("r = ",cor_shoe()))+
   scale_y_continuous(breaks=seq(25, 50, 5))+
   scale_x_continuous(breaks=seq(150, 200, 10))+
  xlab("Height in cm")+
  ylab("Shoe size") +
       scale_color_manual(name = "Study", 
                               breaks = c("Current", "Previous"), 
                               values = c("#00A9FF","#CD9600"),
                               labels = c("Current", "Previous"))+
  theme_bw()+
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
  }

  else if(input$Scatterplotb == "parents"  & input$Scatterplotbc =="all") {
  ggplot()+
   geom_point(data=dataScatterplot(),aes(x=Height_father, y=Height_mother,col=Study),lwd=4)+
   geom_smooth(data=dataScatterplot(),aes(x=Height_father, y=Height_mother),color="black",method = "lm", se = FALSE)+
   geom_point(data=subset(dataScatterplot(),Study=="Current"),aes(x=Height_father, y=Height_mother,col=Study),lwd=4)+
   geom_line(data=scatter_line,aes(x=x, y=y),color="grey",lwd=0.8)+
   annotate("text",  x=155, y=195,size = 8,label=paste("r = ",cor_parents()))+
  scale_y_continuous(breaks=seq(150, 200, 10))+
    scale_x_continuous(breaks=seq(150, 200, 10))+
  xlab("Height of Father")+
  ylab("Height of Mother") +
  scale_color_manual(name = "Study", 
                               breaks = c("Current", "Previous"), 
                               values = c("#00A9FF","#CD9600"),
                               labels = c("Current", "Previous"))+
  theme_bw()+
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
  }
     else if(input$Scatterplotb == "midparent" & input$Scatterplotbc =="own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
  }
  
   else if(input$Scatterplotb == "midparent" & input$Scatterplotbc =="own") {
    ggplot()+
    geom_point(data=subset(dataScatterplot(),Study=="Current"),aes(x=midparent,y=Height_self,col=Study),lwd=4)+
    geom_smooth(data=subset(dataScatterplot(),Study=="Current"),aes(x=midparent,y=Height_self),method = "lm", color="black",se = FALSE)+
    geom_line(data=scatter_line,aes(x=x, y=y),color="grey",lwd=0.8)+
    # annotate("text", x=180, y=165,size = 6, label= paste("r = ",cor_midpar()))+
    # annotate("text", x=180, y=160,size = 6, label= paste("r-squared = ",rsquared_midpar()))+
   annotate("text",  x=160, y=195,size = 8, label= paste("slope = ",slope_midpar()))+
    scale_y_continuous(breaks=seq(150, 200, 10))+
    scale_x_continuous(breaks=seq(150, 200, 10))+
    ylab("Height in cm ")+
    xlab("Midparents Height in cm") +
        scale_color_manual(name = "Study", 
                               breaks = c("Current", "Previous"), 
                               values = c("#00A9FF","#CD9600"),
                               labels = c("Current", "Previous"))+
    theme_bw()+
    theme(axis.ticks.x=element_blank(),
          aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
   }
  
  else if(input$Scatterplotb == "shoe" & input$Scatterplotbc =="own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
  }
  else if(input$Scatterplotb == "shoe"  & input$Scatterplotbc =="own") {
  ggplot()+
   geom_point(data=subset(dataScatterplot(),Study=="Current"),aes(x=Height_self, y=Shoe_size,col=Study),lwd=4)+
   geom_smooth(data=subset(dataScatterplot(),Study=="Current"),aes(x=Height_self, y=Shoe_size),color="black",method = "lm", se = FALSE)+
   annotate("text", x=165, y=46,  size = 8,label=paste("r = ",cor_shoe()))+
  scale_y_continuous(breaks=seq(25, 50, 5))+
   scale_x_continuous(breaks=seq(150, 200, 10))+
  xlab("Height in cm")+
  ylab("Shoe size") +
  scale_color_manual(name = "Study", 
                               breaks = c("Current", "Previous"), 
                               values = c("#00A9FF","#CD9600"),
                               labels = c("Current", "Previous"))+
  theme_bw()+
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
  }

  else if(input$Scatterplotb == "parents" & input$Scatterplotbc =="own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
  }
  else if(input$Scatterplotb == "parents"  & input$Scatterplotbc =="own") {
  ggplot()+
   geom_point(data=subset(dataScatterplot(),Study=="Current"),aes(x=Height_father, y=Height_mother,col=Study),lwd=4)+
   geom_line(data=scatter_line,aes(x=x, y=y),color="grey",lwd=0.8)+
   geom_smooth(data=subset(dataScatterplot(),Study=="Current"),aes(x=Height_father, y=Height_mother),color="black",method = "lm", se = FALSE)+
   annotate("text",  x=155, y=195,size = 8,label=paste("r = ",cor_parents()))+
  scale_y_continuous(breaks=seq(150, 200, 10))+
    scale_x_continuous(breaks=seq(150, 200, 10))+
  xlab("Height of Father")+
  ylab("Height of Mother") +
        scale_color_manual(name = "Study", 
                               breaks = c("Current", "Previous"), 
                               values = c("#00A9FF","#CD9600"),
                               labels = c("Current", "Previous"))+
  theme_bw()+
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
   }
  
})


PlotScatterplot <- reactive({
 if(is.null(data())) { }
  else if(input$Scatterplotb == "midparent" & input$Scatterplotbc =="all") {
    ggplot()+
    geom_point(data=dataScatterplot(),aes(x=midparent,y=Height_self,col=Study),lwd=4)+
    geom_smooth(data=dataScatterplot(),aes(x=midparent,y=Height_self),method = "lm", color="black",se = FALSE)+
    geom_point(data=subset(dataScatterplot(),Study=="Current"),aes(x=midparent,y=Height_self,col= Study),lwd=4)+
    geom_line(data=scatter_line,aes(x=x, y=y),color="grey",lwd=0.8)+
  # annotate("text", x=180, y=165,size = 6, label= paste("r = ",cor_midpar()))+
    # annotate("text", x=180, y=160,size = 6, label= paste("r-squared = ",rsquared_midpar()))+
 annotate("text",  x=160, y=195,size = 8, label= paste("slope = ",slope_midpar()))+
    scale_y_continuous(breaks=seq(150, 200, 10))+
    scale_x_continuous(breaks=seq(150, 200, 10))+
    ylab("Height in cm ")+
    xlab("Midparents Height in cm") +
    scale_color_manual(name = "Study", 
                               breaks = c("Current", "Previous"), 
                               values = c("#00A9FF","#CD9600"),
                               labels = c("Current", "Previous"))+
    theme_bw()+
    theme(axis.ticks.x=element_blank(),
          aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
  }
  else if(input$Scatterplotb == "shoe"  & input$Scatterplotbc =="all") {
  ggplot()+
   geom_point(data=dataScatterplot(),aes(x=Height_self, y=Shoe_size,col=Study),lwd=4)+
   geom_smooth(data=dataScatterplot(),aes(x=Height_self, y=Shoe_size),color="black",method = "lm", se = FALSE)+
   geom_point(data=subset(dataScatterplot(),Study=="Current"),aes(x=Height_self, y=Shoe_size,col=Study),lwd=4)+
     annotate("text", x=165, y=46,  size = 8,label=paste("r = ",cor_shoe()))+
  xlab("Height in cm")+
  ylab("Shoe size") +
       scale_color_manual(name = "Study", 
                               breaks = c("Current", "Previous"), 
                               values = c("#00A9FF","#CD9600"),
                               labels = c("Current", "Previous"))+
  theme_bw()+
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
  }

  else if(input$Scatterplotb == "parents"  & input$Scatterplotbc =="all") {
  ggplot()+
   geom_point(data=dataScatterplot(),aes(x=Height_father, y=Height_mother,col=Study),lwd=4)+
   geom_smooth(data=dataScatterplot(),aes(x=Height_father, y=Height_mother),color="black",method = "lm", se = FALSE)+
   geom_point(data=subset(dataScatterplot(),Study=="Current"),aes(x=Height_father, y=Height_mother,col=Study),lwd=4)+
   geom_line(data=scatter_line,aes(x=x, y=y),color="grey",lwd=0.8)+
   annotate("text",  x=155, y=195,size = 8,label=paste("r = ",cor_parents()))+
  scale_y_continuous(breaks=seq(150, 200, 10))+
    scale_x_continuous(breaks=seq(150, 200, 10))+
  xlab("Height of Father")+
  ylab("Height of Mother") +
  scale_color_manual(name = "Study", 
                               breaks = c("Current", "Previous"), 
                               values = c("#00A9FF","#CD9600"),
                               labels = c("Current", "Previous"))+
  theme_bw()+
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
   }
  
   else if(input$Scatterplotb == "midparent" & input$Scatterplotbc =="own") {
    ggplot()+
    geom_point(data=subset(dataScatterplot(),Study=="Current"),aes(x=midparent,y=Height_self,col=Study),lwd=4)+
    geom_smooth(data=subset(dataScatterplot(),Study=="Current"),aes(x=midparent,y=Height_self),method = "lm", color="black",se = FALSE)+
    geom_line(data=scatter_line,aes(x=x, y=y),color="grey",lwd=0.8)+
  # annotate("text", x=180, y=165,size = 6, label= paste("r = ",cor_midpar()))+
    # annotate("text", x=180, y=160,size = 6, label= paste("r-squared = ",rsquared_midpar()))+
     annotate("text",  x=160, y=195,size = 8, label= paste("slope = ",slope_midpar()))+
    scale_y_continuous(breaks=seq(150, 200, 10))+
    scale_x_continuous(breaks=seq(150, 200, 10))+
    ylab("Height in cm ")+
    xlab("Midparents Height in cm") +
        scale_color_manual(name = "Study", 
                               breaks = c("Current", "Previous"), 
                               values = c("#00A9FF","#CD9600"),
                               labels = c("Current", "Previous"))+
    theme_bw()+
    theme(axis.ticks.x=element_blank(),
          aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
  }
  else if(input$Scatterplotb == "shoe"  & input$Scatterplotbc =="own") {
  ggplot()+
   geom_point(data=subset(dataScatterplot(),Study=="Current"),aes(x=Height_self, y=Shoe_size,col=Study),lwd=4)+
   geom_smooth(data=subset(dataScatterplot(),Study=="Current"),aes(x=Height_self, y=Shoe_size),color="black",method = "lm", se = FALSE)+
   annotate("text", x=165, y=46,  size = 8,label=paste("r = ",cor_shoe()))+
    
  xlab("Height in cm")+
  ylab("Shoe size") +
  scale_color_manual(name = "Study", 
                               breaks = c("Current", "Previous"), 
                               values = c("#00A9FF","#CD9600"),
                               labels = c("Current", "Previous"))+
  theme_bw()+
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
  }

  else if(input$Scatterplotb == "parents"  & input$Scatterplotbc =="own") {
  ggplot()+
   geom_point(data=subset(dataScatterplot(),Study=="Current"),aes(x=Height_father, y=Height_mother,col=Study),lwd=4)+
   geom_line(data=scatter_line,aes(x=x, y=y),color="grey",lwd=0.8)+
   geom_smooth(data=subset(dataScatterplot(),Study=="Current"),aes(x=Height_father, y=Height_mother),color="black",method = "lm", se = FALSE)+
   annotate("text",  x=155, y=195,size = 8,label=paste("r = ",cor_parents()))+
  scale_y_continuous(breaks=seq(150, 200, 10))+
    scale_x_continuous(breaks=seq(150, 200, 10))+
  xlab("Height of Father")+
  ylab("Height of Mother") +
        scale_color_manual(name = "Study", 
                               breaks = c("Current", "Previous"), 
                               values = c("#00A9FF","#CD9600"),
                               labels = c("Current", "Previous"))+
  theme_bw()+
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
   }
  
  
  
})

output$downloadScatterplot <- downloadHandler(
    filename = function() { paste("PlotScatterplot", 'pdf', sep='.') },
    content = function(file) {
      ggsave(file,PlotScatterplot())
    }
  )


observe({
    if(input$NextSE > 0){
      session$sendCustomMessage("myCallbackHandler", "4")
    }
})

# # # # # # # # # # # # # # # # # # # #
# third navbarpage - Central tendency # 
# # # # # # # # # # # # # # # # # # # #

dataMean <- reactive({
 if (input$Meanb == "all") {
 dataMean <- data()
 }
  else {
    dataMean <- data()
    dataMean <- dataMean[dataMean$Study=="Current",]
    dataMean$Study <- as.factor(dataMean$Study)
    }
 return(dataMean)
 })


modusmale <- reactive({
datamale <- dataMean()[dataMean()$Sex==1,]
modusmale <- as.numeric(mlv(datamale$Height_self, method = "mfv")$M[1])
return(modusmale)
})

modusfemale <- reactive({
datafemale <- dataMean()[dataMean()$Sex==2,]
modusfemale <- as.numeric(mlv(datafemale$Height_self, method = "mfv")$M[1])
return(modusfemale)
})

# plot mean, median, modus

output$MeanPlot <- renderPlot({
 if(input$Meanb == "own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
  }
  else {
  ggplot()+
   geom_histogram(data=dataMean(), aes(x=Height_self,fill = Sex),alpha = 0.5,position="identity",color="darkgrey",binwidth=1)+
      
  geom_vline(data=subset(dataMean(),Sex==1),aes(xintercept = mean(Height_self),linetype = "Mean"),col="black",size=1)+
  geom_vline(data=subset(dataMean(),Sex==2),aes(xintercept = mean(Height_self),linetype = "Mean"),col="black",size=1)+
  geom_vline(data=subset(dataMean(),Sex==1),aes(xintercept = median(Height_self),linetype ="Median"),col="black",size=1)+
  geom_vline(data=subset(dataMean(),Sex==2),aes(xintercept = median(Height_self),linetype ="Median"),col="black",size=1)+
  geom_vline(aes(xintercept = modusmale(),linetype = "Mode"),col="black",size=1)    +
  geom_vline(aes(xintercept = modusfemale(),linetype = "Mode"),col="black",size=1)    +
  xlab("Height in cm")+
  ylab("Count") +
      
 scale_linetype_manual(name = "Central tendency", values = c( Mean = "solid", Median = "dashed",Mode="dotted"))+
      
 scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                labels = c("Men", "Women"))+
   theme_bw()+
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
  }
})

PlotCentralTendency <- reactive({
   if(input$Meanb == "own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
  }
  else {
  ggplot()+
   geom_histogram(data=dataMean(), aes(x=Height_self,fill = Sex),alpha = 0.5,position="identity",color="darkgrey",binwidth=1)+
      
  geom_vline(data=subset(dataMean(),Sex==1),aes(xintercept = mean(Height_self),linetype = "Mean"),col="black",size=1)+
  geom_vline(data=subset(dataMean(),Sex==2),aes(xintercept = mean(Height_self),linetype = "Mean"),col="black",size=1)+
  geom_vline(data=subset(dataMean(),Sex==1),aes(xintercept = median(Height_self),linetype ="Median"),col="black",size=1)+
  geom_vline(data=subset(dataMean(),Sex==2),aes(xintercept = median(Height_self),linetype ="Median"),col="black",size=1)+
  geom_vline(aes(xintercept = modusmale(),linetype = "Mode"),col="black",size=1)    +
  geom_vline(aes(xintercept = modusfemale(),linetype = "Mode"),col="black",size=1)    +
  xlab("Height in cm")+
  ylab("Count") +
      
 scale_linetype_manual(name = "Central tendency", values = c( Mean = "solid", Median = "dashed",Mode="dotted"))+
      
 scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                labels = c("Men", "Women"))+
   theme_bw()+
   theme(axis.ticks.x=element_blank(),
         aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
  }
})

output$downloadPlot2 <- downloadHandler(
    filename = function() { paste("PlotCentralTendency", 'pdf', sep='.') },
    content = function(file) {
      ggsave(file,PlotCentralTendency())
    }
  )


# table summary
dataMeanSummary <- reactive({
    if(input$Meanb == "own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
  }
    else {
    dataset <- dataMean()
    data_N <-  aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=length)
    data_min <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=min,na.rm=TRUE)
    data_max <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=max,na.rm=TRUE)
    data_mean <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=mean,na.rm=TRUE)
    data_median <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=median,na.rm=TRUE)
    data_modus <- data.frame(mode=c(modusmale(),modusfemale()))
    data_summarytext <- data.frame(N=data_N,Min=data_min,Max=data_max,mean= data_mean,median=data_median)
    data_summarytext <- data_summarytext[,c(2,4,6,8,10)]
    data_summarytext <- cbind(data_summarytext,data_modus )
    datadiff <- apply(data_summarytext,2,diff)
    data_diff <- as.numeric(datadiff)
    dataMeanSummary <- rbind(data_summarytext,data_diff)
    colnames(dataMeanSummary)  <-c("Sample Size","Min in cm","Max in cm","Mean in cm","Median in cm","Mode in cm")
    dataMeanSummary$Sex <- c("Men","Women","Difference")
    dataMeanSummary <- dataMeanSummary[,c(7,1,2,3,4,5,6)]
    dataMeanSummary[,2]<- as.integer(dataMeanSummary[,2])
    dataMeanSummary[,5] <- round(dataMeanSummary[,5],2)
    dataMeanSummary[,6] <- round(dataMeanSummary[,6],2)
    dataMeanSummary[,7] <- round(dataMeanSummary[,7],2)
    dataMeanSummary <- as.data.frame(dataMeanSummary)
    rownames(dataMeanSummary) <- c()
    return(dataMeanSummary)
    }
  })


output$MeanTable <- renderDataTable({
   if(input$Meanb == "own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
   }
  else {
  datatable(dataMeanSummary(),options = list(dom = 't'),rownames= FALSE)%>%formatStyle('Sex',target = 'row',color = styleEqual(c("Men", "Women"), c('#00A9FF', '#F8766D')))
  }
})


output$downloadData2 <- downloadHandler(
    filename = function() {
      paste("Summary_Mean_Median","xls", sep = ".")
	  },
    content = function(file) {
      write.table(dataMeanSummary(), file, sep="\t",row.names=FALSE)
    }
    )


observe({
    if(input$NextDispersionparameter > 0){
      session$sendCustomMessage("myCallbackHandler", "2")
    }
})
  
# # # # # # # # # # # # # # # # # # # # # # 
# fourth navbarpage - Dispersion parameter # 
# # # # # # # # # # # # # # # # # # # # # #

dataIQR <- reactive({
 if (input$IQRb == "all") {
 dataIQR  <- data()
 }
  else {
    dataIQR <- data()
    dataIQR <- dataIQR[dataIQR$Study=="Current",]
    dataIQR$Study <- as.factor(dataIQR$Study)
    }
 return(dataIQR)
 })


# plot beispiel


# output$IQRimage <-renderUI({
#      my_picture <- tags$iframe(
#      src = "https://drive.google.com/file/d/1OlHLh45nE0ak1DUltIMYAKT3B5ijszOP/preview",
#      width = 480,
#      height = 640,
#      frameborder = 0,
#      marginheight = 0)
#      print(my_picture)
#      my_picture
# 
#     })


output$IQRPlot <- renderPlot({
  if(input$IQRb == "own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
  }
  else {
    ggplot(data=dataIQR())+
          geom_boxplot(data=dataIQR(),aes(y=Height_self,fill=Sex),position=pdb,outlier.colour = "green")+
           xlab("Study")+
           ylab("Height in cm")+
            scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                               labels = c("Men", "Women"))+
   theme_bw()+
   theme( aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
  }
})

set.seed(100)

sample_df <- data.frame(parameter = "test",
                        values = sample(500))

# Extend the top whisker a bit:
sample_df$values[1:100] <- 701:800
# Make sure there's only 1 lower outlier:
sample_df$values[1] <- -350

ggplot2_boxplot <- function(x){
  
  quartiles <- as.numeric(quantile(x, 
                                   probs = c(0.25, 0.5, 0.75)))
  
     names(quartiles) <- c("1.Quartile (Q1)", 
                          "2.Quartile (Q2)",
                          "3.Quartile (Q3)")
  
  IQR <- diff(quartiles[c(1,3)])

  upper_whisker <- max(x[x < (quartiles[3] + 1.5 * IQR)])
  lower_whisker <- min(x[x > (quartiles[1] - 1.5 * IQR)])
    
  upper_dots <- x[x > (quartiles[3] + 1.5*IQR)]
  lower_dots <- x[x < (quartiles[1] - 1.5*IQR)]

  return(list("quartiles" = quartiles,
              "1.Quartile (Q1)" = as.numeric(quartiles[1]),
              "2.Quartile (Q2)" = as.numeric(quartiles[2]),
              "3.Quartile (Q3)" = as.numeric(quartiles[3]),
              "IQR" = IQR,
              "upper_whisker" = upper_whisker,
              "lower_whisker" = lower_whisker,
              "upper_dots" = upper_dots,
              "lower_dots" = lower_dots))
}

ggplot_output <- ggplot2_boxplot(sample_df$values)

ggplot_box_legend <- function(family = "serif"){
  
  # Create data to use in the boxplot legend:
  set.seed(100)

  sample_df <- data.frame(parameter = "test",
                        values = sample(500))

  # Extend the top whisker a bit:
  sample_df$values[1:100] <- 701:800
  # Make sure there's only 1 lower outlier:
  sample_df$values[1] <- -350
  
  # Function to calculate important values:
  ggplot2_boxplot <- function(x){
  
    quartiles <- as.numeric(quantile(x, 
                                     probs = c(0.25, 0.5, 0.75)))
    
    names(quartiles) <- c("1.Quartile (Q1)", 
                          "2.Quartile (Q2)",
                          "3.Quartile (Q3)")
    
    IQR <- diff(quartiles[c(1,3)])
  
    upper_whisker <- max(x[x < (quartiles[3] + 1.5 * IQR)])
    lower_whisker <- min(x[x > (quartiles[1] - 1.5 * IQR)])
      
    upper_dots <- x[x > (quartiles[3] + 1.5*IQR)]
    lower_dots <- x[x < (quartiles[1] - 1.5*IQR)]
  
    return(list("quartiles" = quartiles,
              "1.Quartile (Q1)" = as.numeric(quartiles[1]),
              "2.Quartile (Q2)" = as.numeric(quartiles[2]),
              "3.Quartile (Q3)" = as.numeric(quartiles[3]),
              "IQR" = IQR,
              "upper_whisker" = upper_whisker,
              "lower_whisker" = lower_whisker,
              "upper_dots" = upper_dots,
              "lower_dots" = lower_dots))
  }
  
  # Get those values:
  ggplot_output <- ggplot2_boxplot(sample_df$values)
  
  # Lots of text in the legend, make it smaller and consistent font:
  update_geom_defaults("text", 
                     list(size = 5, 
                          hjust = 0,
                          family = family))
  # Labels don't inherit text:
  update_geom_defaults("label", 
                     list(size = 5, 
                          hjust = 0,
                          family = family))
  
  # Create the legend:
  # The main elements of the plot (the boxplot, error bars, and count)
  # are the easy part.
  # The text describing each of those takes a lot of fiddling to
  # get the location and style just right:
  explain_plot <- ggplot() +
    stat_boxplot(data = sample_df,
                 aes(x = parameter, y=values),
                 geom ='errorbar', width = 0.3) +
    geom_boxplot(data = sample_df,
                 aes(x = parameter, y=values), 
                 width = 0.3, fill = "lightgrey") +
    
    theme_minimal(base_size = 5, base_family = family) +
    geom_segment(aes(x = 2.3, xend = 2.3, 
                     y = ggplot_output[["1.Quartile (Q1)"]], 
                     yend = ggplot_output[["3.Quartile (Q3)"]])) +
    geom_segment(aes(x = 1.2, xend = 2.3, 
                     y = ggplot_output[["1.Quartile (Q1)"]], 
                     yend = ggplot_output[["1.Quartile (Q1)"]])) +
    geom_segment(aes(x = 1.2, xend = 2.3, 
                     y = ggplot_output[["3.Quartile (Q3)"]], 
                     yend = ggplot_output[["3.Quartile (Q3)"]])) +
    geom_text(aes(x = 2.4, y = ggplot_output[["2.Quartile (Q2)"]]), 
              label = "Interquartile\nrange (IQR)",,
              vjust = 0.4) +
    geom_text(aes(x = c(1.17,1.17), 
                  y = c(ggplot_output[["upper_whisker"]],
                        ggplot_output[["lower_whisker"]]), 
                  label = c("Largest value within 1.5 times\nIQR above Q3",
                            "Smallest value within 1.5 times\nIQR below Q1")),
                   vjust = 0.9) +
    geom_text(aes(x = c(1.17), 
                  y =  ggplot_output[["lower_dots"]], 
                  label = "Outside value"), 
              vjust = 0.5) +
   
    geom_label(aes(x = 1.17, y = ggplot_output[["quartiles"]], 
                  label = names(ggplot_output[["quartiles"]])),
              vjust = c(0.4,0.85,0.4), 
              fill = "white", label.size = 0) +
    ylab("") + xlab("") +
    theme(axis.text = element_blank(),
          axis.ticks = element_blank(),
          panel.grid = element_blank(),
          aspect.ratio = 4/3,
          plot.title = element_text(hjust = 0.5, size = 10)) +
    coord_cartesian(xlim = c(1.4,3.1), ylim = c(-600, 900))

  return(explain_plot) 
}


output$IQRExplanation <- renderPlot ({
  
  ggplot_box_legend() 

})
  
PlotIQR <- reactive({
  if(input$IQRb == "own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
  }
  else {
    
    ggplot()+
          stat_boxplot(data=dataIQR(),aes(y=Height_self,fill=as.factor(Sex)),position=pdb,geom ='errorbar')+
          xlab("Study")+
           ylab("Height in cm")+
            scale_fill_manual(name = " ", 
                               breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                labels = c("Men", "Women"))+
   theme_bw()+
   theme( aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
  }
})


output$downloadData3 <- downloadHandler(
    filename = function() { paste("PlotIQR", 'pdf', sep='.') },
    content = function(file) {
      ggsave(file,PlotIQR())
    }
  )


# table summary
dataSummaryIQR <- reactive({
   if(input$IQRb == "own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
  }
    else {
    dataset <- dataIQR()
    data_min <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=min,na.rm=TRUE) 
    data_max <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=max,na.rm=TRUE) 
    data_range <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=range,na.rm=TRUE) 
    data_range2 <- cbind(abs(apply(data_range[,-1],1, diff,na.rm=TRUE)))
    data_perc1 <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=quantile,na.rm=TRUE,0.25) 
    # data_perc2 <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=quantile,na.rm=TRUE,0.5)
    data_perc3 <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=quantile,na.rm=TRUE,0.75)
    data_IQR <- aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=IQR,na.rm=TRUE) 
    data_sd <- round((aggregate(dataset$Height_self, by=list(dataset$Sex), FUN=sd,na.rm=TRUE)[2]),1)
    data_summarytext <- cbind(data_min,data_max,data_range2,data_perc1,data_perc3,data_IQR,data_sd)
    data_summarytext <- data_summarytext[,c(2,4,5,7,9,11,12)]
    datadiff <- apply(data_summarytext,2,diff)
    data_diff <- as.numeric(datadiff)
    dataSummaryIQR <- rbind(data_summarytext,data_diff)
    colnames(dataSummaryIQR)  <-c("Min in cm","Max in cm","Range in cm","Q1 in cm ","Q3 in cm","IQR in cm","SD in cm")
    dataSummaryIQR$Sex <- c("Men","Women","Difference")
    dataSummaryIQR <- dataSummaryIQR[,c(8,1,2,3,4,5,6,7)]
    dataSummaryIQR <- as.data.frame(dataSummaryIQR)
    rownames(dataSummaryIQR) <- c()
    return(dataSummaryIQR)
    }
  })


output$IQRTable <- renderDataTable({
   if(input$IQRb == "own" & length(which(data()$Study=="Current"))==0) {
    return(NULL)
   }
  else {
  datatable(dataSummaryIQR(),options = list(dom = 't'),rownames= FALSE)%>%formatStyle('Sex',target = 'row',color = styleEqual(c("Men", "Women"), c('#00A9FF', '#F8766D')))
  }
})


output$downloadTableIQR <- downloadHandler(
    filename = function() {
      paste("Summary_IQR","xls", sep = ".")
	  },
    content = function(file) {
      write.table(dataSummaryIQR(), file, sep="\t",row.names=FALSE)
    }
    )

  
observe({
    if(input$NextDescriptive > 0){
      session$sendCustomMessage("myCallbackHandler", "3")
    }
  })

  
# # # # # # # # # # # # # # # # # # 
# fifth navbarpage - SE and 95%CI # 
# # # # # # # # # # # # # # # # # # 

data_CI <- reactive({
        dataCI <- data()
        data_mean <- aggregate(dataCI$Height_self,by=list(dataCI$Sex,dataCI$Study), FUN=mean, na.rm=TRUE)  
        data_length <- aggregate(dataCI$Height_self,by=list(dataCI$Sex,dataCI$Study), FUN=length) 
        data_CIl <- aggregate(dataCI$Height_self, by=list(dataCI$Sex,dataCI$Study),
                              function(x) {
                               mean(x,na.rm=TRUE)-(1.96*(sd(x,na.rm=TRUE)/sqrt(length(x))))
                              })
        data_CIu <- aggregate(dataCI$Height_self, by=list(dataCI$Sex,dataCI$Study),
                              function(x) {
                               mean(x,na.rm=TRUE)+(1.96*(sd(x,na.rm=TRUE)/sqrt(length(x))))
                              })
        data_se <- aggregate(dataCI$Height_self, by=list(dataCI$Sex,dataCI$Study),
                              function(x) {sd(x,na.rm=TRUE)/sqrt(length(x))
                              })
        data_sd <- aggregate(dataCI$Height_self, by=list(dataCI$Sex,dataCI$Study),
                              function(x) {sd(x,na.rm=TRUE)
                              })
        
        data_CI <- cbind(data_mean, data_length,data_se,data_sd,data_CIl, data_CIu)  
       data_CI <- data.frame(Sex=data_CI[,1],Study=data_CI[,2],
                      mean=round(data_CI[,3],1),length=data_CI[,6],se=round(data_CI[,9],1),sd=round(data_CI[,12],1),
                      CIl=round(data_CI[,15],1)
                      ,CIu=round(data_CI[,18],1))
        return(data_CI)
})

data_CI_all <- reactive({
        dataCI <- data()
        data_mean <- aggregate(dataCI$Height_self,by=list(dataCI$Sex), FUN=mean, na.rm=TRUE)  
        data_length <- aggregate(dataCI$Height_self,by=list(dataCI$Sex), FUN=length) 
        data_CIl <- aggregate(dataCI$Height_self, by=list(dataCI$Sex),
                              function(x) {
                               mean(x,na.rm=TRUE)-(1.96*(sd(x,na.rm=TRUE)/sqrt(length(x))))
                              })
        data_CIu <- aggregate(dataCI$Height_self, by=list(dataCI$Sex),
                              function(x) {
                               mean(x,na.rm=TRUE)+(1.96*(sd(x,na.rm=TRUE)/sqrt(length(x))))
                              })
        data_se <- aggregate(dataCI$Height_self, by=list(dataCI$Sex,dataCI$Study),
                              function(x) {sd(x,na.rm=TRUE)/sqrt(length(x))
                              })
        data_sd <- aggregate(dataCI$Height_self, by=list(dataCI$Sex,dataCI$Study),
                              function(x) {sd(x,na.rm=TRUE)
                              })
        data_CI_all <- cbind(data_mean, data_length,data_se,data_sd,data_CIl, data_CIu)  
        data_CI_all <- data.frame(Sex=data_CI_all[,1],mean=round(data_CI_all[,2],1),
                          length=data_CI_all[,4],se=round(data_CI_all[,7],1),sd=round(data_CI_all[,10],1),
                          CIl=round(data_CI_all[,12],1),
                          CIu=round(data_CI_all[,14],1))
        return(data_CI_all)
})


data_CI_own <- reactive({
        dataCI <- data()[data()$Study=="Current",]
        data_mean <- aggregate(dataCI$Height_self,by=list(dataCI$Sex), FUN=mean, na.rm=TRUE)  
        data_sd <- aggregate(dataCI$Height_self,by=list(dataCI$Sex), FUN=sd, na.rm=TRUE)  
        data_length <- aggregate(dataCI$Height_self,by=list(dataCI$Sex), FUN=length) 
        data_CIl <- aggregate(dataCI$Height_self, by=list(dataCI$Sex),
                              function(x) {
                               mean(x,na.rm=TRUE)-(1.96*(sd(x,na.rm=TRUE)/sqrt(length(x))))
                              })
        data_CIu <- aggregate(dataCI$Height_self, by=list(dataCI$Sex),
                              function(x) {
                               mean(x,na.rm=TRUE)+(1.96*(sd(x,na.rm=TRUE)/sqrt(length(x))))
                              })
        data_se <- aggregate(dataCI$Height_self, by=list(dataCI$Sex,dataCI$Study),
                              function(x) {sd(x,na.rm=TRUE)/sqrt(length(x))
                              })
       data_sd <- aggregate(dataCI$Height_self, by=list(dataCI$Sex,dataCI$Study),
                              function(x) {sd(x,na.rm=TRUE)
                              })
        
        data_sd <- aggregate(dataCI$Height_self, by=list(dataCI$Sex,dataCI$Study),
                              function(x) {sd(x,na.rm=TRUE)
                              })
        data_CI_own <- cbind(data_mean,data_length,data_se,data_sd,data_CIl, data_CIu)  
        data_CI_own <- data.frame(Sex= data_CI_own[,1],mean=round(data_CI_own[,2],1),
                          length= data_CI_own[,4],se=round(data_CI_own[,7],1),sd=round(data_CI_own[,10],1),
                          CIl=round( data_CI_own[,12],1),
                          CIu=round( data_CI_own[,14],1))
      
        return(data_CI_own)
})


output$SEPlot <- renderPlot({
     if (length(which(data()$Study=="Current"))==0) { 
      ggplot()+
      geom_point(data=data_CI_all(),
                 aes(x="All",y=mean,size=length,col=as.factor(Sex)), position=pd)+
      geom_errorbar(data=data_CI_all(),
                    aes(x="All",ymin=CIl, ymax=CIu,col=as.factor(Sex)),
                    lwd=lwd_errorbar,width=0.5, position=pd)+ 
      labs(size="Sample size")+
      xlab("Study")+
      ylab("Mean height in cm and 95% CI") +
       scale_color_manual(name = " ", 
                                breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                labels = c("Men", "Women"))+
       theme_bw()+
       theme(
          # aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
     }
       
  else if (length(which(data()$Study=="Current"))!=0) { 
      ggplot()+
      geom_point(data=data_CI()[data_CI()$Study=="Current",],aes(x=as.factor(Study),y=mean,size=length,col=as.factor(Sex)), position=pd)+
      geom_errorbar(data=data_CI()[data_CI()$Study=="Current",],aes(x=as.factor(Study),ymin=CIl, ymax=CIu,col=as.factor(Sex)),
                    lwd=lwd_errorbar,width=0.5, position=pd)+
      geom_point(data=data_CI_all(),
                 aes(x="All",y=mean,size=length,col=as.factor(Sex)), position=pd)+
      geom_errorbar(data=data_CI_all(),
                    aes(x="All",ymin=CIl, ymax=CIu,col=as.factor(Sex)),
                    lwd=lwd_errorbar,width=0.5, position=pd)+ 
      labs(size="Sample size")+
      xlab("Study")+
      ylab("Mean height in cm and 95% CI") +
       scale_color_manual(name = " ", 
                                breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                labels = c("Men", "Women"))+
       theme_bw()+
       theme(
          # aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
   }
})

PlotCI <- reactive({
     if(is.null(data_CI())) { }
   else {
      ggplot()+
      geom_point(data=data_CI(),aes(x=as.factor(Study),y=mean,size=length,col=as.factor(Sex)), position=pd)+
      geom_errorbar(data=data_CI(),aes(x=as.factor(Study),ymin=CIl, ymax=CIu,col=as.factor(Sex)),
                    lwd=lwd_errorbar,width=0.5, position=pd)+
        
      geom_point(data=data_CI_all(),
                 aes(x="All",y=mean,size=length,col=as.factor(Sex)), position=pd)+
      geom_errorbar(data=data_CI_all(),
                    aes(x="All",ymin=CIl, ymax=CIu,col=as.factor(Sex)),
                    lwd=lwd_errorbar,width=0.5, position=pd)+ 
       
       labs(size="Sample size")+
       xlab("Study")+
       ylab("Mean height in cm and 95% CI") +
       scale_color_manual(name = " ", 
                                breaks = c("1", "2"), 
                                values = c("#00A9FF","#F8766D"),
                                labels = c("Men", "Women"))+
       theme_bw()+
       theme(
          aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
   }
})

output$downloadData4 <- downloadHandler(
    filename = function() { paste("PlotCI", 'pdf', sep='.') },
    content = function(file) {
      ggsave(file,PlotCI())
    }
  )

CIsummary <- reactive ({
  data_CI_all1 <- data_CI_all()
  data_CI_all1$Study <- "All"
  data_CI_all2 <- data_CI()
  CIsummary <- rbind(data_CI_all2,data_CI_all1)
  CIsummary  <- as.data.frame(CIsummary)
  CIsummary <- CIsummary[,c(2,1,4,3,6,5,7,8)]
  colnames(CIsummary) <- c("Study","Sex","Sample size","Mean in cm ","SD","SE","Lower 95% CI","Upper 95% CI")
  CIsummary$Sex <- as.character(CIsummary$Sex)
  CIsummary$Sex[CIsummary$Sex==1] <- "Men"
  CIsummary$Sex[CIsummary$Sex==2] <- "Women"
  CIsummary <- as.data.frame(CIsummary)
  rownames(CIsummary) <- c()
  if (length(CIsummary[CIsummary$Study=="Current"])==0){
    CIsummary <- CIsummary[CIsummary$Study=="All",]
  }
  else if (length(CIsummary[CIsummary$Study=="Current"])!=0){
     CIsummary <- CIsummary[! CIsummary$Study=="Previous",]
  }
  return(CIsummary)
})

output$SETablet<- renderDataTable({
  datatable(CIsummary(),options = list(dom = 't'),rownames= FALSE)%>%formatStyle('Sex',target = 'row',color = styleEqual(c("Men", "Women"), c('#00A9FF', '#F8766D')))
})

output$downloadTableSE <- downloadHandler(
    filename = function() {
      paste("Summary_CI","xls", sep = ".")
	  },
    content = function(file) {
      write.table(CIsummary(), file, sep="\t",row.names=FALSE)
    }
)

observe({
    if(input$NextTtest > 0){
      session$sendCustomMessage("myCallbackHandler", "5")
    }
})

# # # # # # # # # # # # # # #
# sixth navbarpage - T-Test # 
# # # # # # # # # # # # # # # 


# T-Test Male

ResultsMaleAll <-  reactive({
  dataTestMaleAll <-  data()[data()$Sex==1,]
  pValueMaleAll <- round(t.test(dataTestMaleAll$Height_self, dataTestMaleAll$Height_father,paired = TRUE)$p.value,2)
  ConfLowerMaleAll <- round(t.test(dataTestMaleAll$Height_self, dataTestMaleAll$Height_father,paired = TRUE)$conf.int[1],2)
  ConfUpperMaleAll <- round(t.test(dataTestMaleAll$Height_self, dataTestMaleAll$Height_father,paired = TRUE)$conf.int[2],2)
  
  Mean1MaleAll <- t.test(dataTestMaleAll$Height_self, dataTestMaleAll$Height_father,paired = TRUE)$estimate
  MeanMaleAll <- round(as.numeric(Mean1MaleAll),2)
  MeanHeight_selfMaleAll <- round(as.numeric(mean(dataTestMaleAll$Height_self)),2)
  MeanHeight_fatherMaleAll <-round(as.numeric(mean(dataTestMaleAll$Height_father)),2)
  ResultsMaleAll <- data.frame(pValueMaleAll,ConfLowerMaleAll,ConfUpperMaleAll,MeanMaleAll,MeanHeight_selfMaleAll,MeanHeight_fatherMaleAll)

  ResultsMaleAll$Study <- "All"
  ResultsMaleAll <- ResultsMaleAll[,c(7,5,6,4,2,3,1)]
  colnames(ResultsMaleAll) <- c("Study","Mean_Height","Mean_height_father","Mean_diff","CI_lower","CI_upper","p_value")
  return(ResultsMaleAll)
})

 ResultsMalefinal <- reactive({
 ResultsMalefinal <- ResultsMaleAll()
 return(ResultsMalefinal)
 })

output$tTestMaleResultsplot <- renderPlot({
ggplot(ResultsMalefinal(), aes(x=Mean_diff, y = as.factor(Study))) +
    geom_vline(aes(xintercept = 0), size = .25, linetype = "dashed") +
    geom_errorbarh(aes(xmax = CI_upper, xmin = CI_lower), size = .5, height =.2, color = "gray50") +
    geom_point(size = 3.5, color = "#00A9FF")+
    xlab(expression(" " %<-% "Fathers taller - Mean differences in cm - Male students taller" %->% " "))+
    ylab("Study") +
    scale_x_continuous(breaks=seq(-20, 20,10))+
    coord_cartesian(xlim = c(-20, 20))+
    theme_bw()+
    theme(axis.ticks.x=element_blank(),
          aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=12),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"),
         axis.title.x = element_text(hjust=0.3))

})

ResultsMalefinalp<-  reactive({
    ResultsMalefinalp <-  ResultsMalefinal()
    colnames(ResultsMalefinalp) <- c("Study","Mean male students in cm","Mean father in cm","Mean difference in cm","Lower 95% CI","Upper 95% CI","p-Value")
    ResultsMalefinalp <- as.data.frame(ResultsMalefinalp)
    rownames(ResultsMalefinalp) <- c()
    return(ResultsMalefinalp)

})

output$tTestMaleResults <- renderDataTable({
  datatable(ResultsMalefinalp(),options = list(dom = 't'),rownames= FALSE)%>%formatStyle("Mean difference in cm",color = '#00A9FF')
})

tTestMaleResultsPlotPrint <- reactive({
ggplot(ResultsMalefinal(), aes(x=Mean_diff, y = as.factor(Study))) +
    geom_vline(aes(xintercept = 0), size = .25, linetype = "dashed") +
    geom_errorbarh(aes(xmax = CI_upper, xmin = CI_lower), size = .5, height =.2, color = "gray50") +
    geom_point(size = 3.5, color = "#00A9FF")+
    xlab(expression(" " %<-% "Fathers taller - Mean differences in cm - Male students taller" %->% " "))+
    ylab("Study") +
    scale_x_continuous(breaks=seq(-20, 20,10))+
    coord_cartesian(xlim = c(-20, 20))+
    theme_bw()+
    theme(axis.ticks.x=element_blank(),
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=12),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"),
          axis.title.x = element_text(hjust=0.3))


})

output$downloadtTestMalePlot <- downloadHandler(
    filename = function() { paste("PlotTTestMale", 'pdf', sep='.') },
    content = function(file) {
      ggsave(file,tTestMaleResultsPlotPrint())
    }
  )

output$downloadtTestMaleTable <- downloadHandler(
    filename = function() {
      paste("TTest_Male","xls", sep = ".")
	  },
    content = function(file) {
      write.table(ResultsMalefinal(), file, sep="\t",row.names=FALSE)
    }
)

# T-Test Female

ResultsFemaleAll <-  reactive({
  dataTestFemaleAll <-  data()[data()$Sex==2,]
  pValueFemaleAll <- round(t.test(dataTestFemaleAll$Height_self, dataTestFemaleAll$Height_mother,paired = TRUE)$p.value,2)
  ConfLowerFemaleAll <- round(t.test(dataTestFemaleAll$Height_self,dataTestFemaleAll$Height_mother,paired = TRUE)$conf.int[1],2)
  ConfUpperFemaleAll <- round(t.test(dataTestFemaleAll$Height_self,dataTestFemaleAll$Height_mother,paired = TRUE)$conf.int[2],2)
  Mean1FemaleAll <- t.test(dataTestFemaleAll$Height_self, dataTestFemaleAll$Height_mother,paired = TRUE)$estimate
  MeanFemaleAll <- round(as.numeric(Mean1FemaleAll),2)
  
  MeanHeight_selfFemaleAll <- round(as.numeric(mean(dataTestFemaleAll$Height_self)),2)
  MeanHeight_motherFemaleAll <- round(as.numeric(mean(dataTestFemaleAll$Height_mother)),2)
  ResultsFemaleAll <- data.frame(pValueFemaleAll,ConfLowerFemaleAll,ConfUpperFemaleAll,MeanFemaleAll,MeanHeight_selfFemaleAll,MeanHeight_motherFemaleAll)
  
  ResultsFemaleAll$Study <- "All"
  ResultsFemaleAll <- ResultsFemaleAll[,c(7,5,6,4,2,3,1)]
  colnames(ResultsFemaleAll) <- c("Study","Mean_Height","Mean_height_mother","Mean_diff","CI_lower","CI_upper","p_value")
  return(ResultsFemaleAll)
})

ResultsFemalefinal <- reactive({
ResultsFemalefinal <- ResultsFemaleAll()
return(ResultsFemalefinal)
})

output$tTestFemaleResultsplot <- renderPlot({
ggplot(ResultsFemalefinal(), aes(x =Mean_diff, y = as.factor(Study))) +
    geom_vline(aes(xintercept = 0), size = .25, linetype = "dashed") +
    geom_errorbarh(aes(xmax = CI_upper, xmin = CI_lower), size = .5, height =
                    .2, color = "gray50") +
    geom_point(size = 3.5, color = "#F8766D")+
    xlab(expression(" " %<-% "Mothers taller - Mean differences in cm - Female students taller" %->% " "))+
    ylab("Study") +
     scale_x_continuous(breaks=seq(-20, 20,10))+
    coord_cartesian(xlim = c(-20, 20))+
    theme_bw()+
    theme(axis.ticks.x=element_blank(),
          aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=12),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"),
        axis.title.x = element_text(hjust=0.3))



})

ResultsFemalefinalp <-  reactive({
     ResultsFemalefinalp <- ResultsFemalefinal()
     colnames(ResultsFemalefinalp) <- c("Study","Mean female students in cm","Mean mother in cm","Mean difference in cm","Lower 95% CI","Upper 95% CI","p-Value")
     ResultsFemalefinalp <- as.data.frame(ResultsFemalefinalp)
     rownames(ResultsFemalefinalp) <- c()
     return(ResultsFemalefinalp)
})

output$tTestFemaleResults <- renderDataTable({
  datatable(ResultsFemalefinalp(),options = list(dom = 't'),rownames= FALSE)%>%formatStyle("Mean difference in cm",color = '#F8766D')
})

tTestFemaleResultsplotPrint <- reactive({
ggplot(ResultsFemalefinal(), aes(x =Mean_diff, y = as.factor(Study))) +
    geom_vline(aes(xintercept = 0), size = .25, linetype = "dashed") +
    geom_errorbarh(aes(xmax = CI_upper, xmin = CI_lower), size = .5, height =
                    .2, color = "gray50") +
    geom_point(size = 3.5, color = "#F8766D")+
    xlab(expression(" " %<-% "Mothers taller - Mean differences in cm - Female students taller" %->% " "))+
    ylab("Study") +
    scale_x_continuous(breaks=seq(-20, 20,10))+
    coord_cartesian(xlim = c(-20, 20))+
    theme_bw()+
    theme(axis.ticks.x=element_blank(),
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=12),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"),
           axis.title.x = element_text(hjust=0.3))


})

output$downloadtTestFemalePlot <- downloadHandler(
    filename = function() { paste("PlotTTestFemale", 'pdf', sep='.') },
    content = function(file) {
      ggsave(file,tTestFemaleResultsplotPrint())
    }
  )

output$downloadtTestFemaleTable <- downloadHandler(
    filename = function() {
      paste("TTest_Female","xls", sep = ".")
	  },
    content = function(file) {
      write.table(ResultsFemalefinal(), file, sep="\t",row.names=FALSE)
    }
)

# T-Test Milk

datamilk <- reactive({
  datamilk <- data()
  datamilk$MilkGroup <- datamilk$Milk
  datamilk$MilkGroup <- as.numeric(datamilk$MilkGroup)
  if (input$MilkGroup=="Group1") {
  datamilk$MilkGroup[datamilk$MilkGroup==0 ] <- 5
  datamilk$MilkGroup[datamilk$MilkGroup==1 | datamilk$MilkGroup==2 | datamilk$MilkGroup==3 | datamilk$MilkGroup==4] <- 6
  datamilk <- datamilk[!is.na(datamilk$MilkGroup),]
  }
  else if (input$MilkGroup=="Group2") {

  datamilk$MilkGroup[datamilk$MilkGroup==0 | datamilk$MilkGroup==1] <- 5
  datamilk$MilkGroup[datamilk$MilkGroup==2 | datamilk$MilkGroup==3 | datamilk$MilkGroup==4] <- 6
  datamilk <- datamilk[!is.na(datamilk$MilkGroup),]
  }
  else if (input$MilkGroup=="Group3") {
  datamilk$MilkGroup[datamilk$MilkGroup==0 | datamilk$MilkGroup==1 | datamilk$MilkGroup==2]  <- 5
  datamilk$MilkGroup[datamilk$MilkGroup==3 | datamilk$MilkGroup==4] <- 6
  datamilk <- datamilk[!is.na(datamilk$MilkGroup),]
  }
  return(datamilk)
})


ResultsMilkMale <-  reactive({
  dataTestMilkMale <-  datamilk()[datamilk()$Sex==1,]
  pValueMilkMale <- round(t.test(dataTestMilkMale$Height_self[dataTestMilkMale$MilkGroup==5],
                                 dataTestMilkMale$Height_self[dataTestMilkMale$MilkGroup==6])$p.value,2)
  ConfLowerMilkMale <- round(t.test(dataTestMilkMale$Height_self[dataTestMilkMale$MilkGroup==5],
                                 dataTestMilkMale$Height_self[dataTestMilkMale$MilkGroup==6])$conf.int[1],2)
  ConfUpperMilkMale <- round(t.test(dataTestMilkMale$Height_self[dataTestMilkMale$MilkGroup==5],
                                 dataTestMilkMale$Height_self[dataTestMilkMale$MilkGroup==6])$conf.int[2],2)
  Mean1MilkMale <- round(t.test(dataTestMilkMale$Height_self[dataTestMilkMale$MilkGroup==6],
                                 dataTestMilkMale$Height_self[dataTestMilkMale$MilkGroup==5])$estimate[1],2)
  Mean2MilkMale <- round(t.test(dataTestMilkMale$Height_self[dataTestMilkMale$MilkGroup==6],
                                 dataTestMilkMale$Height_self[dataTestMilkMale$MilkGroup==5])$estimate[2],2)
  MeanMilkMale <- round(as.numeric(Mean2MilkMale-Mean1MilkMale),2)
  ResultsMilkMale <- data.frame(pValueMilkMale,ConfLowerMilkMale,ConfUpperMilkMale,MeanMilkMale,Mean1MilkMale,Mean2MilkMale)
  return(ResultsMilkMale)

})

ResultsMilkMale2 <-  reactive({
  ResultsMilkMale2 <-  ResultsMilkMale()
  ResultsMilkMale2$Sex <- 1
  ResultsMilkMale2 <- ResultsMilkMale2[,c(5,6,4,2,3,1,7)]
  colnames(ResultsMilkMale2) <- c("Mean_less","Mean_more","Mean_diff","CI_lower","CI_upper","p_value","Sex")
  return(ResultsMilkMale2)
})


# Female

ResultsMilkFemale <-  reactive({
  dataTestMilkFemale <-  datamilk()[datamilk()$Sex==2,]
  pValueMilkFemale <- round(t.test(dataTestMilkFemale$Height_self[dataTestMilkFemale$MilkGroup==5],
                                 dataTestMilkFemale$Height_self[dataTestMilkFemale$MilkGroup==6])$p.value,2)
  ConfLowerMilkFemale <- round(t.test(dataTestMilkFemale$Height_self[dataTestMilkFemale$MilkGroup==5],
                                 dataTestMilkFemale$Height_self[dataTestMilkFemale$MilkGroup==6])$conf.int[1],2)
  ConfUpperMilkFemale <- round(t.test(dataTestMilkFemale$Height_self[dataTestMilkFemale$MilkGroup==5],
                                 dataTestMilkFemale$Height_self[dataTestMilkFemale$MilkGroup==6])$conf.int[2],2)
  Mean1MilkFemale <- round(t.test(dataTestMilkFemale$Height_self[dataTestMilkFemale$MilkGroup==6],
                                 dataTestMilkFemale$Height_self[dataTestMilkFemale$MilkGroup==5])$estimate[1],2)
  Mean2MilkFemale <- round(t.test(dataTestMilkFemale$Height_self[dataTestMilkFemale$MilkGroup==6],
                                 dataTestMilkFemale$Height_self[dataTestMilkFemale$MilkGroup==5])$estimate[2],2)
  MeanMilkFemale <- round(as.numeric(Mean2MilkFemale - Mean1MilkFemale),2)
  ResultsMilkFemale <- data.frame(pValueMilkFemale,ConfLowerMilkFemale,ConfUpperMilkFemale,MeanMilkFemale, Mean1MilkFemale, Mean2MilkFemale)
  return(ResultsMilkFemale)

})

ResultsMilkFemale2 <-  reactive({
  ResultsMilkFemale2 <-  ResultsMilkFemale()
  ResultsMilkFemale2$Sex <- 2
  ResultsMilkFemale2 <- ResultsMilkFemale2[,c(5,6,4,2,3,1,7)]
  colnames(ResultsMilkFemale2) <-c("Mean_less","Mean_more","Mean_diff","CI_lower","CI_upper","p_value","Sex")
  return(ResultsMilkFemale2)
})

ResultsMilkfinal <- reactive({
ResultsMilkfinal <- rbind(ResultsMilkMale2(),ResultsMilkFemale2())
ResultsMilkfinal <- ResultsMilkfinal[,c(7,1,2,3,4,5,6)]
colnames(ResultsMilkfinal)[1] <- "Sex"
return(ResultsMilkfinal)

})

output$tTestMilkResultsplot <- renderPlot({
  if(is.null(ResultsMilkfinal())) { }
  else{
ggplot(ResultsMilkfinal(), aes(x =Mean_diff, y = as.factor(Sex))) +
    geom_vline(aes(xintercept = 0), size = .25, linetype = "dashed") +
    geom_errorbarh(aes(xmax = CI_upper, xmin = CI_lower), size = .5, height =.2, color = "gray50") +
    geom_point(size = 3.5,aes(col = as.factor(ResultsMilkfinal()$Sex)))+
    scale_y_discrete(breaks=c(1,2),
                     labels = c("Men","Women"))+
    scale_color_manual(values=c("#00A9FF","#F8766D"))+
    xlab(expression(" " %<-% "Drinking less - Mean differences in cm - Drinking more" %->% " "))+
    ylab("Study") +
    scale_x_continuous(breaks=seq(-20, 20,10))+
    coord_cartesian(xlim = c(-20, 20))+
    theme_bw()+
   theme(axis.ticks.x=element_blank(),
          aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          strip.text.x = element_text(size = size_strip_text),
         axis.title.x = element_text(hjust=0.5),
          legend.position="none")
}
})



tTestMilkResultsTablet <- reactive({
if(is.null(ResultsMilkfinal())) { }
  else{
ResultsMilkfinal <- ResultsMilkfinal()
ResultsMilkfinal$Sex[ResultsMilkfinal$Sex==1] <- "Men"
ResultsMilkfinal$Sex[ResultsMilkfinal$Sex==2] <- "Women"
colnames(ResultsMilkfinal) <- c("Sex","Mean height in cm - less milk","Mean height in cm - more milk","Mean difference in cm","Lower 95% CI","Upper 95% CI","p-Value")
ResultsMilkfinal <- as.data.frame(ResultsMilkfinal)
rownames(ResultsMilkfinal) <- c()
return(ResultsMilkfinal)
  }
})


output$tTestMilkResultsTable <- renderDataTable({
  datatable(tTestMilkResultsTablet(),options = list(dom = 't'),rownames= FALSE)%>%formatStyle('Mean difference in cm','Sex',color = styleEqual(c("Men", "Women"), c('#00A9FF', '#F8766D')))
})

tTestMilkResultsplotPrint <- reactive({
if(is.null(ResultsMilkfinal())) { }
  else{
ggplot(ResultsMilkfinal(), aes(x =Mean_diff, y = as.factor(Sex))) +
    geom_vline(aes(xintercept = 0), size = .25, linetype = "dashed") +
    geom_errorbarh(aes(xmax = CI_upper, xmin = CI_lower), size = .5, height =.2, color = "gray50") +
    geom_point(size = 3.5,aes(col = as.factor(ResultsMilkfinal()$Sex)))+
    scale_y_discrete(breaks=c(1,2),
                     labels = c("Men","Women"))+
    scale_color_manual(values=c("#00A9FF","#F8766D"))+
    xlab(expression(" " %<-% "Drinking less - Mean differences in cm - Drinking more" %->% " "))+
    ylab("Study") +
    scale_x_continuous(breaks=seq(-20, 20,10))+
    coord_cartesian(xlim = c(-20, 20))+
    theme_bw()+
   theme(axis.ticks.x=element_blank(),
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          strip.text.x = element_text(size = size_strip_text),
         axis.title.x = element_text(hjust=0.5),
          legend.position="none")
}

})

output$downloadtTestMilkPlot <- downloadHandler(
    filename = function() { paste("PlotTTestMilk", 'pdf', sep='.') },
    content = function(file) {
      ggsave(file,tTestMilkResultsplotPrint())
    }
  )

output$downloadtTestMilkTable <- downloadHandler(
    filename = function() {
      paste("TTest_Milk","xls", sep = ".")
	  },
    content = function(file) {
      write.table(ResultsMilkfinal(), file, sep="\t",row.names=FALSE)
    }
)

observe({
    if(input$NextSimulation > 0){
      session$sendCustomMessage("myCallbackHandler", "6")
    }
})


# # # # # # # # # # # # # # # # # # #
# seventh navbarpage - Simulation 1 # 
# # # # # # # # # # # # # # # # # # #

# Simulation Sample Size

df_men <- reactive({
    set.seed(123)
    df_men <- data.frame(height=rnorm(input$SamplesizeMenb, mean=178, sd=7),
                         sex=as.factor(rep(1,input$SamplesizeMenb)))
                     })

df_women <- reactive({
    set.seed(123)
    df_women <- data.frame(height=rnorm(input$SamplesizeWomenb, mean=166, sd=7),
                           sex=as.factor(rep(2,input$SamplesizeWomenb)))
                     })

df_all <- reactive({
    df_all <- rbind(df_women(),df_men())
})

output$SimulationSamplesizeHistPlot <- renderPlot({
  ggplot(data=df_all())+
  geom_histogram(aes(x=height,y=..density..,fill = sex),position="identity",alpha = 0.5)+
  # geom_density(aes(x=height,y=..density..,color = sex),lwd=1,show_guide = FALSE)+
  xlim(120,220)+
  xlab("Height in cm")+
  ylab("Proportion") +
    scale_fill_manual( name="Sex",
                       values=c("#F8766D","#00A9FF"),
                       breaks=c("1", "2"),
                       labels=c("Men", "Women"))+
    theme_bw()+
    theme(aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
    })

output$SimulationSamplesizeBoxPlot <- renderPlot({
    ggplot()+
    geom_boxplot(data=df_all(),aes(x=sex,y=height,fill=sex))+
    ylim(120,220)+
    scale_fill_manual( name="Sex",
                        values=c("#F8766D","#00A9FF"),
                       breaks=c("1", "2"),
                       labels=c("Men", "Women"))+
    ylab("Height in cm")+
    theme_bw()+
    theme(aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
})

# Simulation Mean
df_men2 <- reactive({
  set.seed(123)
    df_men2 <- data.frame(height=rnorm(250, mean=input$MeanMenb, sd=7),
                         sex=as.factor(rep(1,250)))
                     })

df_women2 <- reactive({
  set.seed(123)
    df_women2 <- data.frame(height=rnorm(250, mean=input$MeanWomenb, sd=7),
                           sex=as.factor(rep(2,250)))
                     })

df_all2 <- reactive({
    df_all2 <- rbind(df_women2(),df_men2())
})

output$SimulationMeanHistPlot <- renderPlot({
  ggplot(data=df_all2())+
  geom_histogram(aes(x=height,y=..density..,fill = sex),position="identity",alpha = 0.5)+
  # geom_density(aes(x=height,y=..density..,color = sex),lwd=1,show_guide = FALSE)+
      xlab("Height in cm")+
  ylab("Proportion") +
      xlim(120,220)+
    scale_fill_manual( name="Sex",
                        values=c("#F8766D","#00A9FF"),
                       breaks=c("1", "2"),
                       labels=c("Men", "Women"))+
    theme_bw()+
    theme(aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
    })

output$SimulationMeanBoxPlot <- renderPlot({
    ggplot()+
    geom_boxplot(data=df_all2(),aes(x=sex,y=height,fill=sex))+
    ylim(120,220)+
    scale_fill_manual( name="Sex",
                        values=c("#F8766D","#00A9FF"),
                       breaks=c("1", "2"),
                       labels=c("Men", "Women"))+
      ylab("Height in cm")+
    theme_bw()+
    theme(aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
})

# Simulation SD
df_men3 <- reactive({
  set.seed(123)
    df_men3 <- data.frame(height=rnorm(250, mean=178, sd=input$SDmenb),
                         sex=as.factor(rep(1,250)))
                     })

df_women3 <- reactive({
  set.seed(123)
    df_women3 <- data.frame(height=rnorm(250, mean=166, sd=input$SDwomenb),
                           sex=as.factor(rep(2,250)))
                     })

df_all3 <- reactive({
    df_all3 <- rbind(df_women3(),df_men3())
    return(df_all3)
})

output$SimulationSDHistPlot <- renderPlot({
  ggplot(data=df_all3())+
  geom_histogram(aes(x=height,y=..density..,fill = sex),position="identity",alpha = 0.5)+
     xlim(120,220)+
     xlab("Height in cm")+
  ylab("Proportion") +
    scale_fill_manual( name="Sex",
                        values=c("#F8766D","#00A9FF"),
                       breaks=c("1", "2"),
                       labels=c("Men", "Women"))+
    theme_bw()+
    theme(aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
    })

output$SimulationSDBoxPlot<- renderPlot({
    ggplot()+
    geom_boxplot(data=df_all3(),aes(x=sex,y=height,fill=sex))+
    ylim(120,220)+
    scale_fill_manual( name="Sex",
                        values=c("#F8766D","#00A9FF"),
                       breaks=c("1", "2"),
                       labels=c("Men", "Women"))+
      ylab("Height in cm")+
    theme_bw()+
    theme(aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
})

# Simulation shape 

height_men <- reactive({
height_men <- rsnorm(250, mean = 178, sd = 7, xi = input$Shape)
})

df_men4 <- reactive({
    df_men4 <- data.frame(height=height_men())
                     })

output$SimulationShapeHistPlot <- renderPlot({
  ggplot(data=df_men4())+
  geom_histogram(aes(x=height,y=..density..),fill="#00A9FF",position="identity",alpha = 0.8)+
  xlab("Height in cm")+
  ylab("Proportion") +
  # geom_density(aes(x=height,y=..density..),lwd=1,show_guide = FALSE)+
    theme_bw()+
    theme(aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
    })

output$SimulationShapeBoxPlot<- renderPlot({
    ggplot()+
    geom_boxplot(data=df_men4(),aes(y=height),fill="#00A9FF",)+
    ylim(120,220)+
    theme_bw()+
    ylab("Height in cm")+
    theme(aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title))
})


observe({
    if(input$NextSimulation2 > 0){
      session$sendCustomMessage("myCallbackHandler", "7")
    }
})

# # # # # # # # # # # # # # # # # # #
# eighth navbarpage - Simulation 2  # 
# # # # # # # # # # # # # # # # # # #

# sample size
df_men_mean <- reactive({
    set.seed(123)
    df_men_mean <- data.frame(height=rnorm(input$SamplesizeCIMenb, mean=178, sd=7),
                         sex=as.factor(rep(1,input$SamplesizeCIMenb)))
                     })

df_women_mean <- reactive({
    set.seed(123)
    df_women_mean <- data.frame(height=rnorm(input$SamplesizeCIWomenb, mean=166, sd=7),
                           sex=as.factor(rep(2,input$SamplesizeCIWomenb)))
                     })

df_all_mean <- reactive({
    df_all_mean <- rbind(df_women_mean(),df_men_mean())
    df_all_mean
})

data_CI_sim <- reactive({
        dataCI <- df_all_mean()
        data_mean <- aggregate(dataCI$height,by=list(dataCI$sex), FUN=mean, na.rm=TRUE)  
        data_length <- aggregate(dataCI$height,by=list(dataCI$sex), FUN=length) 
        data_CIl <- aggregate(dataCI$height, by=list(dataCI$sex),
                              function(x) {
                               mean(x,na.rm=TRUE)-(1.96*(sd(x,na.rm=TRUE)/sqrt(length(x))))
                              })
        data_CIu <- aggregate(dataCI$height, by=list(dataCI$sex),
                              function(x) {
                               mean(x,na.rm=TRUE)+(1.96*(sd(x,na.rm=TRUE)/sqrt(length(x))))
                              })
        
        data_CI_sim <- cbind(data_mean, data_length,data_CIl, data_CIu)  
        data_CI_sim <- data.frame(sex=data_CI_sim[,1],mean=round(data_CI_sim[,2],1),
                                  length=data_CI_sim[,4],CIl=round(data_CI_sim[,6],1),
                                  CIu=round(data_CI_sim[,8],1))
        return(data_CI_sim)
})

output$SimulationCISamplesizePlot <- renderPlot({
      ggplot()+
      geom_point(data=data_CI_sim(),
                 aes(x="",y=mean,col=as.factor(sex)), position=pd)+
      geom_errorbar(data=data_CI_sim(),
                    aes(x="",ymin=CIl, ymax=CIu,col=as.factor(sex)),
                    lwd=lwd_errorbar,width=0.5, position=pd)+ 
       
      labs(size="Sample size")+
      xlab("")+
      ylab("Mean height in cm and 95% CI") +
      ylim(150,190)+
       scale_color_manual(name = " ", 
                                breaks = c("1", "2"), 
                                 values=c("#F8766D","#00A9FF"),
                                labels = c("Men", "Women"))+
       theme_bw()+
       theme(aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
})

# Mean
df_men_mean2 <- reactive({
  set.seed(123)
    df_men_mean2 <- data.frame(height=rnorm(100, mean=input$MeanCIMenb, sd=20),
                         sex=as.factor(rep(1,100)))
                     })

df_women_mean2 <- reactive({
  set.seed(123)
    df_women_mean2 <- data.frame(height=rnorm(100, mean=input$MeanCIWomenb, sd=20),
                           sex=as.factor(rep(2,100)))
                     })

df_all_mean2 <- reactive({
    df_all_mean2 <- rbind(df_women_mean2(),df_men_mean2())
    df_all_mean2
})

data_CI_sim2 <- reactive({
        dataCI <- df_all_mean2()
        data_mean <- aggregate(dataCI$height,by=list(dataCI$sex), FUN=mean, na.rm=TRUE)  
        data_length <- aggregate(dataCI$height,by=list(dataCI$sex), FUN=length) 
        data_CIl <- aggregate(dataCI$height, by=list(dataCI$sex),
                              function(x) {
                               mean(x,na.rm=TRUE)-(1.96*(sd(x,na.rm=TRUE)/sqrt(length(x))))
                              })
        data_CIu <- aggregate(dataCI$height, by=list(dataCI$sex),
                              function(x) {
                               mean(x,na.rm=TRUE)+(1.96*(sd(x,na.rm=TRUE)/sqrt(length(x))))
                              })
        
        data_CI_sim2 <- cbind(data_mean, data_length,data_CIl, data_CIu)  
        data_CI_sim2 <- data.frame(sex=data_CI_sim2[,1],mean=round(data_CI_sim2[,2],1),
                                  length=data_CI_sim2[,4],CIl=round(data_CI_sim2[,6],1),
                                  CIu=round(data_CI_sim2[,8],1))
        return(data_CI_sim2)
})

output$SimulationCIMeanPlot <- renderPlot({
      ggplot()+
      geom_point(data=data_CI_sim2(),
                 aes(x="",y=mean,col=as.factor(sex)), position=pd)+
      geom_errorbar(data=data_CI_sim2(),
                    aes(x="",ymin=CIl, ymax=CIu,col=as.factor(sex)),
                    lwd=lwd_errorbar,width=0.5, position=pd)+ 
      ylim(130,210)+ 
      labs(size="Sample size")+
      xlab("")+
      ylab("Mean height in cm and 95% CI") +
       scale_color_manual(name = " ", 
                                breaks = c("1", "2"), 
                                 values=c("#F8766D","#00A9FF"),
                                labels = c("Men", "Women"))+
       theme_bw()+
       theme(aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
})

# SD
df_men_mean3 <- reactive({
  set.seed(123)
    df_men_mean3 <- data.frame(height=rnorm(100, mean=175, sd=input$SDCImenb),
                         sex=as.factor(rep(1,100)))
                     })

df_women_mean3 <- reactive({
  set.seed(123)
    df_women_mean3 <- data.frame(height=rnorm(100, mean=166, sd=input$SDCIwomenb),
                           sex=as.factor(rep(2,100)))
                     })

df_all_mean3 <- reactive({
    df_all_mean3 <- rbind(df_women_mean3(),df_men_mean3())
    df_all_mean3
})

data_CI_sim3 <- reactive({
        dataCI <- df_all_mean3()
        data_mean <- aggregate(dataCI$height,by=list(dataCI$sex), FUN=mean, na.rm=TRUE)  
        data_length <- aggregate(dataCI$height,by=list(dataCI$sex), FUN=length) 
        data_CIl <- aggregate(dataCI$height, by=list(dataCI$sex),
                              function(x) {
                               mean(x,na.rm=TRUE)-(1.96*(sd(x,na.rm=TRUE)/sqrt(length(x))))
                              })
        data_CIu <- aggregate(dataCI$height, by=list(dataCI$sex),
                              function(x) {
                               mean(x,na.rm=TRUE)+(1.96*(sd(x,na.rm=TRUE)/sqrt(length(x))))
                              })
        
        data_CI_sim3 <- cbind(data_mean, data_length,data_CIl, data_CIu)  
        data_CI_sim3 <- data.frame(sex=data_CI_sim3[,1],mean=round(data_CI_sim3[,2],1),
                                  length=data_CI_sim3[,4],CIl=round(data_CI_sim3[,6],1),
                                  CIu=round(data_CI_sim3[,8],1))
        return(data_CI_sim3)
})

output$SimulationCISDPlot<- renderPlot({
      ggplot()+
      geom_point(data=data_CI_sim3(),
                 aes(x="",y=mean,col=as.factor(sex)), position=pd)+
      geom_errorbar(data=data_CI_sim3(),
                    aes(x="",ymin=CIl, ymax=CIu,col=as.factor(sex)),
                    lwd=lwd_errorbar,width=0.5, position=pd)+ 
      ylim(150,190)+
      labs(size="Sample size")+
      xlab("")+
       ylab("Mean height in cm and 95% CI") +
       scale_color_manual(name = " ", 
                                breaks = c("1", "2"), 
                                 values=c("#F8766D","#00A9FF"),
                               labels = c("Men", "Women"))+
       theme_bw()+
       theme(aspect.ratio=1,
          axis.text=element_text(size=size),
          axis.title=element_text(size=size_axis_title),
          title=element_text(size=size_axis_title),
          legend.text=element_text(size=size_axis_title),
          legend.key.size=unit(1.5,"cm"))
})

}

shinyApp(ui = ui, server = server,options = list(height = 1000,width=1400))  

